// Autogenerated from CppHeaderCreator
// Created by Sc2ad
// =========================================================================
#pragma once
// Begin includes
#include "beatsaber-hook/shared/utils/typedefs.h"
#include "beatsaber-hook/shared/utils/byref.hpp"
// Including type: System.Configuration.ConfigurationElementCollection
#include "System/Configuration/ConfigurationElementCollection.hpp"
#include "beatsaber-hook/shared/utils/il2cpp-utils-methods.hpp"
#include "beatsaber-hook/shared/utils/il2cpp-utils-properties.hpp"
#include "beatsaber-hook/shared/utils/il2cpp-utils-fields.hpp"
#include "beatsaber-hook/shared/utils/utils.h"
#include "beatsaber-hook/shared/utils/typedefs-string.hpp"
// Completed includes
// Begin forward declares
// Forward declaring namespace: System::Net::Configuration
namespace System::Net::Configuration {
  // Forward declaring type: WebRequestModuleElement
  class WebRequestModuleElement;
}
// Forward declaring namespace: System::Configuration
namespace System::Configuration {
  // Skipping declaration: ConfigurationElement because it is already included!
}
// Completed forward declares
// Type namespace: System.Net.Configuration
namespace System::Net::Configuration {
  // Forward declaring type: WebRequestModuleElementCollection
  class WebRequestModuleElementCollection;
}
#include "beatsaber-hook/shared/utils/il2cpp-type-check.hpp"
NEED_NO_BOX(::System::Net::Configuration::WebRequestModuleElementCollection);
DEFINE_IL2CPP_ARG_TYPE(::System::Net::Configuration::WebRequestModuleElementCollection*, "System.Net.Configuration", "WebRequestModuleElementCollection");
// Type namespace: System.Net.Configuration
namespace System::Net::Configuration {
  // Size: 0x10
  #pragma pack(push, 1)
  // Autogenerated type: System.Net.Configuration.WebRequestModuleElementCollection
  // [TokenAttribute] Offset: FFFFFFFF
  // [DefaultMemberAttribute] Offset: A603D4
  // [ConfigurationCollectionAttribute] Offset: A603D4
  class WebRequestModuleElementCollection : public ::System::Configuration::ConfigurationElementCollection {
    public:
    // public System.Void .ctor()
    // Offset: 0x126F930
    template<::il2cpp_utils::CreationType creationType = ::il2cpp_utils::CreationType::Temporary>
    static WebRequestModuleElementCollection* New_ctor() {
      static auto ___internal__logger = ::Logger::get().WithContext("::System::Net::Configuration::WebRequestModuleElementCollection::.ctor");
      return THROW_UNLESS((::il2cpp_utils::New<WebRequestModuleElementCollection*, creationType>()));
    }
    // public System.Net.Configuration.WebRequestModuleElement get_Item(System.Int32 index)
    // Offset: 0x126F970
    ::System::Net::Configuration::WebRequestModuleElement* get_Item(int index);
    // public System.Void set_Item(System.Int32 index, System.Net.Configuration.WebRequestModuleElement value)
    // Offset: 0x126F9B0
    void set_Item(int index, ::System::Net::Configuration::WebRequestModuleElement* value);
    // public System.Net.Configuration.WebRequestModuleElement get_Item(System.String name)
    // Offset: 0x126F9F0
    ::System::Net::Configuration::WebRequestModuleElement* get_Item(::StringW name);
    // public System.Void set_Item(System.String name, System.Net.Configuration.WebRequestModuleElement value)
    // Offset: 0x126FA30
    void set_Item(::StringW name, ::System::Net::Configuration::WebRequestModuleElement* value);
    // public System.Void Add(System.Net.Configuration.WebRequestModuleElement element)
    // Offset: 0x126FA70
    void Add(::System::Net::Configuration::WebRequestModuleElement* element);
    // public System.Void Clear()
    // Offset: 0x126FAB0
    void Clear();
    // public System.Int32 IndexOf(System.Net.Configuration.WebRequestModuleElement element)
    // Offset: 0x126FB70
    int IndexOf(::System::Net::Configuration::WebRequestModuleElement* element);
    // public System.Void Remove(System.Net.Configuration.WebRequestModuleElement element)
    // Offset: 0x126FBB0
    void Remove(::System::Net::Configuration::WebRequestModuleElement* element);
    // public System.Void Remove(System.String name)
    // Offset: 0x126FBF0
    void Remove(::StringW name);
    // public System.Void RemoveAt(System.Int32 index)
    // Offset: 0x126FC30
    void RemoveAt(int index);
    // protected override System.Configuration.ConfigurationElement CreateNewElement()
    // Offset: 0x126FAF0
    // Implemented from: System.Configuration.ConfigurationElementCollection
    // Base method: System.Configuration.ConfigurationElement ConfigurationElementCollection::CreateNewElement()
    ::System::Configuration::ConfigurationElement* CreateNewElement();
    // protected override System.Object GetElementKey(System.Configuration.ConfigurationElement element)
    // Offset: 0x126FB30
    // Implemented from: System.Configuration.ConfigurationElementCollection
    // Base method: System.Object ConfigurationElementCollection::GetElementKey(System.Configuration.ConfigurationElement element)
    ::Il2CppObject* GetElementKey(::System::Configuration::ConfigurationElement* element);
  }; // System.Net.Configuration.WebRequestModuleElementCollection
  #pragma pack(pop)
}
#include "beatsaber-hook/shared/utils/il2cpp-utils-methods.hpp"
// Writing MetadataGetter for method: System::Net::Configuration::WebRequestModuleElementCollection::New_ctor
// Il2CppName: .ctor
// Cannot get method pointer of value based method overload from template for constructor!
// Try using FindMethod instead!
// Writing MetadataGetter for method: System::Net::Configuration::WebRequestModuleElementCollection::get_Item
// Il2CppName: get_Item
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<::System::Net::Configuration::WebRequestModuleElement* (System::Net::Configuration::WebRequestModuleElementCollection::*)(int)>(&System::Net::Configuration::WebRequestModuleElementCollection::get_Item)> {
  static const MethodInfo* get() {
    static auto* index = &::il2cpp_utils::GetClassFromName("System", "Int32")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(System::Net::Configuration::WebRequestModuleElementCollection*), "get_Item", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{index});
  }
};
// Writing MetadataGetter for method: System::Net::Configuration::WebRequestModuleElementCollection::set_Item
// Il2CppName: set_Item
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (System::Net::Configuration::WebRequestModuleElementCollection::*)(int, ::System::Net::Configuration::WebRequestModuleElement*)>(&System::Net::Configuration::WebRequestModuleElementCollection::set_Item)> {
  static const MethodInfo* get() {
    static auto* index = &::il2cpp_utils::GetClassFromName("System", "Int32")->byval_arg;
    static auto* value = &::il2cpp_utils::GetClassFromName("System.Net.Configuration", "WebRequestModuleElement")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(System::Net::Configuration::WebRequestModuleElementCollection*), "set_Item", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{index, value});
  }
};
// Writing MetadataGetter for method: System::Net::Configuration::WebRequestModuleElementCollection::get_Item
// Il2CppName: get_Item
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<::System::Net::Configuration::WebRequestModuleElement* (System::Net::Configuration::WebRequestModuleElementCollection::*)(::StringW)>(&System::Net::Configuration::WebRequestModuleElementCollection::get_Item)> {
  static const MethodInfo* get() {
    static auto* name = &::il2cpp_utils::GetClassFromName("System", "String")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(System::Net::Configuration::WebRequestModuleElementCollection*), "get_Item", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{name});
  }
};
// Writing MetadataGetter for method: System::Net::Configuration::WebRequestModuleElementCollection::set_Item
// Il2CppName: set_Item
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (System::Net::Configuration::WebRequestModuleElementCollection::*)(::StringW, ::System::Net::Configuration::WebRequestModuleElement*)>(&System::Net::Configuration::WebRequestModuleElementCollection::set_Item)> {
  static const MethodInfo* get() {
    static auto* name = &::il2cpp_utils::GetClassFromName("System", "String")->byval_arg;
    static auto* value = &::il2cpp_utils::GetClassFromName("System.Net.Configuration", "WebRequestModuleElement")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(System::Net::Configuration::WebRequestModuleElementCollection*), "set_Item", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{name, value});
  }
};
// Writing MetadataGetter for method: System::Net::Configuration::WebRequestModuleElementCollection::Add
// Il2CppName: Add
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (System::Net::Configuration::WebRequestModuleElementCollection::*)(::System::Net::Configuration::WebRequestModuleElement*)>(&System::Net::Configuration::WebRequestModuleElementCollection::Add)> {
  static const MethodInfo* get() {
    static auto* element = &::il2cpp_utils::GetClassFromName("System.Net.Configuration", "WebRequestModuleElement")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(System::Net::Configuration::WebRequestModuleElementCollection*), "Add", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{element});
  }
};
// Writing MetadataGetter for method: System::Net::Configuration::WebRequestModuleElementCollection::Clear
// Il2CppName: Clear
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (System::Net::Configuration::WebRequestModuleElementCollection::*)()>(&System::Net::Configuration::WebRequestModuleElementCollection::Clear)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(System::Net::Configuration::WebRequestModuleElementCollection*), "Clear", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: System::Net::Configuration::WebRequestModuleElementCollection::IndexOf
// Il2CppName: IndexOf
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<int (System::Net::Configuration::WebRequestModuleElementCollection::*)(::System::Net::Configuration::WebRequestModuleElement*)>(&System::Net::Configuration::WebRequestModuleElementCollection::IndexOf)> {
  static const MethodInfo* get() {
    static auto* element = &::il2cpp_utils::GetClassFromName("System.Net.Configuration", "WebRequestModuleElement")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(System::Net::Configuration::WebRequestModuleElementCollection*), "IndexOf", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{element});
  }
};
// Writing MetadataGetter for method: System::Net::Configuration::WebRequestModuleElementCollection::Remove
// Il2CppName: Remove
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (System::Net::Configuration::WebRequestModuleElementCollection::*)(::System::Net::Configuration::WebRequestModuleElement*)>(&System::Net::Configuration::WebRequestModuleElementCollection::Remove)> {
  static const MethodInfo* get() {
    static auto* element = &::il2cpp_utils::GetClassFromName("System.Net.Configuration", "WebRequestModuleElement")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(System::Net::Configuration::WebRequestModuleElementCollection*), "Remove", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{element});
  }
};
// Writing MetadataGetter for method: System::Net::Configuration::WebRequestModuleElementCollection::Remove
// Il2CppName: Remove
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (System::Net::Configuration::WebRequestModuleElementCollection::*)(::StringW)>(&System::Net::Configuration::WebRequestModuleElementCollection::Remove)> {
  static const MethodInfo* get() {
    static auto* name = &::il2cpp_utils::GetClassFromName("System", "String")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(System::Net::Configuration::WebRequestModuleElementCollection*), "Remove", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{name});
  }
};
// Writing MetadataGetter for method: System::Net::Configuration::WebRequestModuleElementCollection::RemoveAt
// Il2CppName: RemoveAt
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (System::Net::Configuration::WebRequestModuleElementCollection::*)(int)>(&System::Net::Configuration::WebRequestModuleElementCollection::RemoveAt)> {
  static const MethodInfo* get() {
    static auto* index = &::il2cpp_utils::GetClassFromName("System", "Int32")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(System::Net::Configuration::WebRequestModuleElementCollection*), "RemoveAt", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{index});
  }
};
// Writing MetadataGetter for method: System::Net::Configuration::WebRequestModuleElementCollection::CreateNewElement
// Il2CppName: CreateNewElement
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<::System::Configuration::ConfigurationElement* (System::Net::Configuration::WebRequestModuleElementCollection::*)()>(&System::Net::Configuration::WebRequestModuleElementCollection::CreateNewElement)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(System::Net::Configuration::WebRequestModuleElementCollection*), "CreateNewElement", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: System::Net::Configuration::WebRequestModuleElementCollection::GetElementKey
// Il2CppName: GetElementKey
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<::Il2CppObject* (System::Net::Configuration::WebRequestModuleElementCollection::*)(::System::Configuration::ConfigurationElement*)>(&System::Net::Configuration::WebRequestModuleElementCollection::GetElementKey)> {
  static const MethodInfo* get() {
    static auto* element = &::il2cpp_utils::GetClassFromName("System.Configuration", "ConfigurationElement")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(System::Net::Configuration::WebRequestModuleElementCollection*), "GetElementKey", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{element});
  }
};
