// Autogenerated from CppHeaderCreator
// Created by Sc2ad
// =========================================================================
#pragma once
// Begin includes
#include "beatsaber-hook/shared/utils/byref.hpp"
// Completed includes
// Begin forward declares
// Forward declaring namespace: System::ComponentModel
namespace System::ComponentModel {
  // Forward declaring type: PropertyChangingEventHandler
  class PropertyChangingEventHandler;
}
// Completed forward declares
// Type namespace: System.ComponentModel
namespace System::ComponentModel {
  // Forward declaring type: INotifyPropertyChanging
  class INotifyPropertyChanging;
}
#include "beatsaber-hook/shared/utils/il2cpp-type-check.hpp"
NEED_NO_BOX(::System::ComponentModel::INotifyPropertyChanging);
DEFINE_IL2CPP_ARG_TYPE(::System::ComponentModel::INotifyPropertyChanging*, "System.ComponentModel", "INotifyPropertyChanging");
// Type namespace: System.ComponentModel
namespace System::ComponentModel {
  // Size: 0x0
  #pragma pack(push, 1)
  // Autogenerated type: System.ComponentModel.INotifyPropertyChanging
  // [TokenAttribute] Offset: FFFFFFFF
  class INotifyPropertyChanging {
    public:
    // public System.Void add_PropertyChanging(System.ComponentModel.PropertyChangingEventHandler value)
    // Offset: 0xFFFFFFFFFFFFFFFF
    void add_PropertyChanging(::System::ComponentModel::PropertyChangingEventHandler* value);
    // public System.Void remove_PropertyChanging(System.ComponentModel.PropertyChangingEventHandler value)
    // Offset: 0xFFFFFFFFFFFFFFFF
    void remove_PropertyChanging(::System::ComponentModel::PropertyChangingEventHandler* value);
  }; // System.ComponentModel.INotifyPropertyChanging
  #pragma pack(pop)
}
#include "beatsaber-hook/shared/utils/il2cpp-utils-methods.hpp"
// Writing MetadataGetter for method: System::ComponentModel::INotifyPropertyChanging::add_PropertyChanging
// Il2CppName: add_PropertyChanging
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (System::ComponentModel::INotifyPropertyChanging::*)(::System::ComponentModel::PropertyChangingEventHandler*)>(&System::ComponentModel::INotifyPropertyChanging::add_PropertyChanging)> {
  static const MethodInfo* get() {
    static auto* value = &::il2cpp_utils::GetClassFromName("System.ComponentModel", "PropertyChangingEventHandler")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(System::ComponentModel::INotifyPropertyChanging*), "add_PropertyChanging", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{value});
  }
};
// Writing MetadataGetter for method: System::ComponentModel::INotifyPropertyChanging::remove_PropertyChanging
// Il2CppName: remove_PropertyChanging
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (System::ComponentModel::INotifyPropertyChanging::*)(::System::ComponentModel::PropertyChangingEventHandler*)>(&System::ComponentModel::INotifyPropertyChanging::remove_PropertyChanging)> {
  static const MethodInfo* get() {
    static auto* value = &::il2cpp_utils::GetClassFromName("System.ComponentModel", "PropertyChangingEventHandler")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(System::ComponentModel::INotifyPropertyChanging*), "remove_PropertyChanging", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{value});
  }
};
