// Autogenerated from CppHeaderCreator
// Created by Sc2ad
// =========================================================================
#pragma once
// Begin includes
#include "beatsaber-hook/shared/utils/typedefs.h"
#include "beatsaber-hook/shared/utils/byref.hpp"
// Including type: System.Resources.UltimateResourceFallbackLocation
#include "System/Resources/UltimateResourceFallbackLocation.hpp"
#include "beatsaber-hook/shared/utils/il2cpp-utils-methods.hpp"
#include "beatsaber-hook/shared/utils/il2cpp-utils-properties.hpp"
#include "beatsaber-hook/shared/utils/il2cpp-utils-fields.hpp"
#include "beatsaber-hook/shared/utils/utils.h"
#include "beatsaber-hook/shared/utils/typedefs-string.hpp"
// Completed includes
// Begin forward declares
// Forward declaring namespace: System::Resources
namespace System::Resources {
  // Forward declaring type: ResourceSet
  class ResourceSet;
  // Forward declaring type: IResourceGroveler
  class IResourceGroveler;
}
// Forward declaring namespace: System::Collections
namespace System::Collections {
  // Forward declaring type: Hashtable
  class Hashtable;
}
// Forward declaring namespace: System::Collections::Generic
namespace System::Collections::Generic {
  // Forward declaring type: Dictionary`2<TKey, TValue>
  template<typename TKey, typename TValue>
  class Dictionary_2;
}
// Forward declaring namespace: System::Reflection
namespace System::Reflection {
  // Forward declaring type: Assembly
  class Assembly;
  // Forward declaring type: RuntimeAssembly
  class RuntimeAssembly;
  // Forward declaring type: AssemblyName
  class AssemblyName;
}
// Forward declaring namespace: System
namespace System {
  // Forward declaring type: Type
  class Type;
  // Forward declaring type: Version
  class Version;
}
// Forward declaring namespace: System::Globalization
namespace System::Globalization {
  // Forward declaring type: CultureInfo
  class CultureInfo;
}
// Forward declaring namespace: System::Runtime::Serialization
namespace System::Runtime::Serialization {
  // Forward declaring type: StreamingContext
  struct StreamingContext;
}
// Forward declaring namespace: System::Threading
namespace System::Threading {
  // Forward declaring type: StackCrawlMark
  struct StackCrawlMark;
}
// Completed forward declares
// Type namespace: System.Resources
namespace System::Resources {
  // Forward declaring type: ResourceManager
  class ResourceManager;
}
#include "beatsaber-hook/shared/utils/il2cpp-type-check.hpp"
NEED_NO_BOX(::System::Resources::ResourceManager);
DEFINE_IL2CPP_ARG_TYPE(::System::Resources::ResourceManager*, "System.Resources", "ResourceManager");
// Type namespace: System.Resources
namespace System::Resources {
  // Size: 0x88
  #pragma pack(push, 1)
  // Autogenerated type: System.Resources.ResourceManager
  // [TokenAttribute] Offset: FFFFFFFF
  // [ComVisibleAttribute] Offset: A50C80
  class ResourceManager : public ::Il2CppObject {
    public:
    // Nested type: ::System::Resources::ResourceManager::CultureNameResourceSetPair
    class CultureNameResourceSetPair;
    // Nested type: ::System::Resources::ResourceManager::ResourceManagerMediator
    class ResourceManagerMediator;
    public:
    // protected System.String BaseNameField
    // Size: 0x8
    // Offset: 0x10
    ::StringW BaseNameField;
    // Field size check
    static_assert(sizeof(::StringW) == 0x8);
    // [ObsoleteAttribute] Offset: 0xA57044
    // protected System.Collections.Hashtable ResourceSets
    // Size: 0x8
    // Offset: 0x18
    ::System::Collections::Hashtable* ResourceSets;
    // Field size check
    static_assert(sizeof(::System::Collections::Hashtable*) == 0x8);
    // private System.Collections.Generic.Dictionary`2<System.String,System.Resources.ResourceSet> _resourceSets
    // Size: 0x8
    // Offset: 0x20
    ::System::Collections::Generic::Dictionary_2<::StringW, ::System::Resources::ResourceSet*>* resourceSets;
    // Field size check
    static_assert(sizeof(::System::Collections::Generic::Dictionary_2<::StringW, ::System::Resources::ResourceSet*>*) == 0x8);
    // private System.String moduleDir
    // Size: 0x8
    // Offset: 0x28
    ::StringW moduleDir;
    // Field size check
    static_assert(sizeof(::StringW) == 0x8);
    // protected System.Reflection.Assembly MainAssembly
    // Size: 0x8
    // Offset: 0x30
    ::System::Reflection::Assembly* MainAssembly;
    // Field size check
    static_assert(sizeof(::System::Reflection::Assembly*) == 0x8);
    // private System.Type _locationInfo
    // Size: 0x8
    // Offset: 0x38
    ::System::Type* locationInfo;
    // Field size check
    static_assert(sizeof(::System::Type*) == 0x8);
    // private System.Type _userResourceSet
    // Size: 0x8
    // Offset: 0x40
    ::System::Type* userResourceSet;
    // Field size check
    static_assert(sizeof(::System::Type*) == 0x8);
    // private System.Globalization.CultureInfo _neutralResourcesCulture
    // Size: 0x8
    // Offset: 0x48
    ::System::Globalization::CultureInfo* neutralResourcesCulture;
    // Field size check
    static_assert(sizeof(::System::Globalization::CultureInfo*) == 0x8);
    // private System.Resources.ResourceManager/CultureNameResourceSetPair _lastUsedResourceCache
    // Size: 0x8
    // Offset: 0x50
    ::System::Resources::ResourceManager::CultureNameResourceSetPair* lastUsedResourceCache;
    // Field size check
    static_assert(sizeof(::System::Resources::ResourceManager::CultureNameResourceSetPair*) == 0x8);
    // private System.Boolean _ignoreCase
    // Size: 0x1
    // Offset: 0x58
    bool ignoreCase;
    // Field size check
    static_assert(sizeof(bool) == 0x1);
    // private System.Boolean UseManifest
    // Size: 0x1
    // Offset: 0x59
    bool UseManifest;
    // Field size check
    static_assert(sizeof(bool) == 0x1);
    // [OptionalFieldAttribute] Offset: 0xA5707C
    // private System.Boolean UseSatelliteAssem
    // Size: 0x1
    // Offset: 0x5A
    bool UseSatelliteAssem;
    // Field size check
    static_assert(sizeof(bool) == 0x1);
    // Padding between fields: UseSatelliteAssem and: fallbackLoc
    char __padding11[0x1] = {};
    // [OptionalFieldAttribute] Offset: 0xA570B4
    // private System.Resources.UltimateResourceFallbackLocation _fallbackLoc
    // Size: 0x4
    // Offset: 0x5C
    ::System::Resources::UltimateResourceFallbackLocation fallbackLoc;
    // Field size check
    static_assert(sizeof(::System::Resources::UltimateResourceFallbackLocation) == 0x4);
    // [OptionalFieldAttribute] Offset: 0xA570C4
    // private System.Version _satelliteContractVersion
    // Size: 0x8
    // Offset: 0x60
    ::System::Version* satelliteContractVersion;
    // Field size check
    static_assert(sizeof(::System::Version*) == 0x8);
    // [OptionalFieldAttribute] Offset: 0xA570D4
    // private System.Boolean _lookedForSatelliteContractVersion
    // Size: 0x1
    // Offset: 0x68
    bool lookedForSatelliteContractVersion;
    // Field size check
    static_assert(sizeof(bool) == 0x1);
    // Padding between fields: lookedForSatelliteContractVersion and: callingAssembly
    char __padding14[0x7] = {};
    // [OptionalFieldAttribute] Offset: 0xA570E4
    // private System.Reflection.Assembly _callingAssembly
    // Size: 0x8
    // Offset: 0x70
    ::System::Reflection::Assembly* callingAssembly;
    // Field size check
    static_assert(sizeof(::System::Reflection::Assembly*) == 0x8);
    // [OptionalFieldAttribute] Offset: 0xA5711C
    // private System.Reflection.RuntimeAssembly m_callingAssembly
    // Size: 0x8
    // Offset: 0x78
    ::System::Reflection::RuntimeAssembly* m_callingAssembly;
    // Field size check
    static_assert(sizeof(::System::Reflection::RuntimeAssembly*) == 0x8);
    // private System.Resources.IResourceGroveler resourceGroveler
    // Size: 0x8
    // Offset: 0x80
    ::System::Resources::IResourceGroveler* resourceGroveler;
    // Field size check
    static_assert(sizeof(::System::Resources::IResourceGroveler*) == 0x8);
    public:
    // Get static field: static public readonly System.Int32 MagicNumber
    static int _get_MagicNumber();
    // Set static field: static public readonly System.Int32 MagicNumber
    static void _set_MagicNumber(int value);
    // Get static field: static public readonly System.Int32 HeaderVersionNumber
    static int _get_HeaderVersionNumber();
    // Set static field: static public readonly System.Int32 HeaderVersionNumber
    static void _set_HeaderVersionNumber(int value);
    // Get static field: static private readonly System.Type _minResourceSet
    static ::System::Type* _get__minResourceSet();
    // Set static field: static private readonly System.Type _minResourceSet
    static void _set__minResourceSet(::System::Type* value);
    // Get static field: static readonly System.String ResReaderTypeName
    static ::StringW _get_ResReaderTypeName();
    // Set static field: static readonly System.String ResReaderTypeName
    static void _set_ResReaderTypeName(::StringW value);
    // Get static field: static readonly System.String ResSetTypeName
    static ::StringW _get_ResSetTypeName();
    // Set static field: static readonly System.String ResSetTypeName
    static void _set_ResSetTypeName(::StringW value);
    // Get static field: static readonly System.String MscorlibName
    static ::StringW _get_MscorlibName();
    // Set static field: static readonly System.String MscorlibName
    static void _set_MscorlibName(::StringW value);
    // Get static field: static readonly System.Int32 DEBUG
    static int _get_DEBUG();
    // Set static field: static readonly System.Int32 DEBUG
    static void _set_DEBUG(int value);
    // Get instance field reference: protected System.String BaseNameField
    [[deprecated("Use field access instead!")]] ::StringW& dyn_BaseNameField();
    // Get instance field reference: protected System.Collections.Hashtable ResourceSets
    [[deprecated("Use field access instead!")]] ::System::Collections::Hashtable*& dyn_ResourceSets();
    // Get instance field reference: private System.Collections.Generic.Dictionary`2<System.String,System.Resources.ResourceSet> _resourceSets
    [[deprecated("Use field access instead!")]] ::System::Collections::Generic::Dictionary_2<::StringW, ::System::Resources::ResourceSet*>*& dyn__resourceSets();
    // Get instance field reference: private System.String moduleDir
    [[deprecated("Use field access instead!")]] ::StringW& dyn_moduleDir();
    // Get instance field reference: protected System.Reflection.Assembly MainAssembly
    [[deprecated("Use field access instead!")]] ::System::Reflection::Assembly*& dyn_MainAssembly();
    // Get instance field reference: private System.Type _locationInfo
    [[deprecated("Use field access instead!")]] ::System::Type*& dyn__locationInfo();
    // Get instance field reference: private System.Type _userResourceSet
    [[deprecated("Use field access instead!")]] ::System::Type*& dyn__userResourceSet();
    // Get instance field reference: private System.Globalization.CultureInfo _neutralResourcesCulture
    [[deprecated("Use field access instead!")]] ::System::Globalization::CultureInfo*& dyn__neutralResourcesCulture();
    // Get instance field reference: private System.Resources.ResourceManager/CultureNameResourceSetPair _lastUsedResourceCache
    [[deprecated("Use field access instead!")]] ::System::Resources::ResourceManager::CultureNameResourceSetPair*& dyn__lastUsedResourceCache();
    // Get instance field reference: private System.Boolean _ignoreCase
    [[deprecated("Use field access instead!")]] bool& dyn__ignoreCase();
    // Get instance field reference: private System.Boolean UseManifest
    [[deprecated("Use field access instead!")]] bool& dyn_UseManifest();
    // Get instance field reference: private System.Boolean UseSatelliteAssem
    [[deprecated("Use field access instead!")]] bool& dyn_UseSatelliteAssem();
    // Get instance field reference: private System.Resources.UltimateResourceFallbackLocation _fallbackLoc
    [[deprecated("Use field access instead!")]] ::System::Resources::UltimateResourceFallbackLocation& dyn__fallbackLoc();
    // Get instance field reference: private System.Version _satelliteContractVersion
    [[deprecated("Use field access instead!")]] ::System::Version*& dyn__satelliteContractVersion();
    // Get instance field reference: private System.Boolean _lookedForSatelliteContractVersion
    [[deprecated("Use field access instead!")]] bool& dyn__lookedForSatelliteContractVersion();
    // Get instance field reference: private System.Reflection.Assembly _callingAssembly
    [[deprecated("Use field access instead!")]] ::System::Reflection::Assembly*& dyn__callingAssembly();
    // Get instance field reference: private System.Reflection.RuntimeAssembly m_callingAssembly
    [[deprecated("Use field access instead!")]] ::System::Reflection::RuntimeAssembly*& dyn_m_callingAssembly();
    // Get instance field reference: private System.Resources.IResourceGroveler resourceGroveler
    [[deprecated("Use field access instead!")]] ::System::Resources::IResourceGroveler*& dyn_resourceGroveler();
    // private System.Void Init()
    // Offset: 0x1334C0C
    void Init();
    // public System.Void .ctor(System.String baseName, System.Reflection.Assembly assembly)
    // Offset: 0x1334DF4
    template<::il2cpp_utils::CreationType creationType = ::il2cpp_utils::CreationType::Temporary>
    static ResourceManager* New_ctor(::StringW baseName, ::System::Reflection::Assembly* assembly) {
      static auto ___internal__logger = ::Logger::get().WithContext("::System::Resources::ResourceManager::.ctor");
      return THROW_UNLESS((::il2cpp_utils::New<ResourceManager*, creationType>(baseName, assembly)));
    }
    // public System.Void .ctor(System.Type resourceSource)
    // Offset: 0x1335128
    template<::il2cpp_utils::CreationType creationType = ::il2cpp_utils::CreationType::Temporary>
    static ResourceManager* New_ctor(::System::Type* resourceSource) {
      static auto ___internal__logger = ::Logger::get().WithContext("::System::Resources::ResourceManager::.ctor");
      return THROW_UNLESS((::il2cpp_utils::New<ResourceManager*, creationType>(resourceSource)));
    }
    // private System.Void OnDeserializing(System.Runtime.Serialization.StreamingContext ctx)
    // Offset: 0x1335370
    void OnDeserializing(::System::Runtime::Serialization::StreamingContext ctx);
    // private System.Void OnDeserialized(System.Runtime.Serialization.StreamingContext ctx)
    // Offset: 0x1335380
    void OnDeserialized(::System::Runtime::Serialization::StreamingContext ctx);
    // private System.Void OnSerializing(System.Runtime.Serialization.StreamingContext ctx)
    // Offset: 0x13354DC
    void OnSerializing(::System::Runtime::Serialization::StreamingContext ctx);
    // private System.Void CommonAssemblyInit()
    // Offset: 0x1335018
    void CommonAssemblyInit();
    // public System.String get_BaseName()
    // Offset: 0x133554C
    ::StringW get_BaseName();
    // public System.Boolean get_IgnoreCase()
    // Offset: 0x1335554
    bool get_IgnoreCase();
    // protected System.Resources.UltimateResourceFallbackLocation get_FallbackLocation()
    // Offset: 0x133555C
    ::System::Resources::UltimateResourceFallbackLocation get_FallbackLocation();
    // protected System.String GetResourceFileName(System.Globalization.CultureInfo culture)
    // Offset: 0x1335564
    ::StringW GetResourceFileName(::System::Globalization::CultureInfo* culture);
    // System.Resources.ResourceSet GetFirstResourceSet(System.Globalization.CultureInfo culture)
    // Offset: 0x1335698
    ::System::Resources::ResourceSet* GetFirstResourceSet(::System::Globalization::CultureInfo* culture);
    // public System.Resources.ResourceSet GetResourceSet(System.Globalization.CultureInfo culture, System.Boolean createIfNotExists, System.Boolean tryParents)
    // Offset: 0x1335A1C
    ::System::Resources::ResourceSet* GetResourceSet(::System::Globalization::CultureInfo* culture, bool createIfNotExists, bool tryParents);
    // protected System.Resources.ResourceSet InternalGetResourceSet(System.Globalization.CultureInfo culture, System.Boolean createIfNotExists, System.Boolean tryParents)
    // Offset: 0x1335EDC
    ::System::Resources::ResourceSet* InternalGetResourceSet(::System::Globalization::CultureInfo* culture, bool createIfNotExists, bool tryParents);
    // private System.Resources.ResourceSet InternalGetResourceSet(System.Globalization.CultureInfo requestedCulture, System.Boolean createIfNotExists, System.Boolean tryParents, ref System.Threading.StackCrawlMark stackMark)
    // Offset: 0x1335F0C
    ::System::Resources::ResourceSet* InternalGetResourceSet(::System::Globalization::CultureInfo* requestedCulture, bool createIfNotExists, bool tryParents, ByRef<::System::Threading::StackCrawlMark> stackMark);
    // static private System.Void AddResourceSet(System.Collections.Generic.Dictionary`2<System.String,System.Resources.ResourceSet> localResourceSets, System.String cultureName, ref System.Resources.ResourceSet rs)
    // Offset: 0x1335D40
    static void AddResourceSet(::System::Collections::Generic::Dictionary_2<::StringW, ::System::Resources::ResourceSet*>* localResourceSets, ::StringW cultureName, ByRef<::System::Resources::ResourceSet*> rs);
    // static protected System.Version GetSatelliteContractVersion(System.Reflection.Assembly a)
    // Offset: 0x1336670
    static ::System::Version* GetSatelliteContractVersion(::System::Reflection::Assembly* a);
    // static protected System.Globalization.CultureInfo GetNeutralResourcesLanguage(System.Reflection.Assembly a)
    // Offset: 0x1336D88
    static ::System::Globalization::CultureInfo* GetNeutralResourcesLanguage(::System::Reflection::Assembly* a);
    // static System.Boolean CompareNames(System.String asmTypeName1, System.String typeName2, System.Reflection.AssemblyName asmName2)
    // Offset: 0x13343D8
    static bool CompareNames(::StringW asmTypeName1, ::StringW typeName2, ::System::Reflection::AssemblyName* asmName2);
    // private System.Void SetAppXConfiguration()
    // Offset: 0x1335014
    void SetAppXConfiguration();
    // public System.String GetString(System.String name, System.Globalization.CultureInfo culture)
    // Offset: 0x1336DAC
    ::StringW GetString(::StringW name, ::System::Globalization::CultureInfo* culture);
    // static private System.Void .cctor()
    // Offset: 0x133720C
    static void _cctor();
    // protected System.Void .ctor()
    // Offset: 0x1334C94
    // Implemented from: System.Object
    // Base method: System.Void Object::.ctor()
    template<::il2cpp_utils::CreationType creationType = ::il2cpp_utils::CreationType::Temporary>
    static ResourceManager* New_ctor() {
      static auto ___internal__logger = ::Logger::get().WithContext("::System::Resources::ResourceManager::.ctor");
      return THROW_UNLESS((::il2cpp_utils::New<ResourceManager*, creationType>()));
    }
  }; // System.Resources.ResourceManager
  #pragma pack(pop)
  static check_size<sizeof(ResourceManager), 128 + sizeof(::System::Resources::IResourceGroveler*)> __System_Resources_ResourceManagerSizeCheck;
  static_assert(sizeof(ResourceManager) == 0x88);
}
#include "beatsaber-hook/shared/utils/il2cpp-utils-methods.hpp"
// Writing MetadataGetter for method: System::Resources::ResourceManager::Init
// Il2CppName: Init
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (System::Resources::ResourceManager::*)()>(&System::Resources::ResourceManager::Init)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(System::Resources::ResourceManager*), "Init", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: System::Resources::ResourceManager::New_ctor
// Il2CppName: .ctor
// Cannot get method pointer of value based method overload from template for constructor!
// Try using FindMethod instead!
// Writing MetadataGetter for method: System::Resources::ResourceManager::New_ctor
// Il2CppName: .ctor
// Cannot get method pointer of value based method overload from template for constructor!
// Try using FindMethod instead!
// Writing MetadataGetter for method: System::Resources::ResourceManager::OnDeserializing
// Il2CppName: OnDeserializing
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (System::Resources::ResourceManager::*)(::System::Runtime::Serialization::StreamingContext)>(&System::Resources::ResourceManager::OnDeserializing)> {
  static const MethodInfo* get() {
    static auto* ctx = &::il2cpp_utils::GetClassFromName("System.Runtime.Serialization", "StreamingContext")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(System::Resources::ResourceManager*), "OnDeserializing", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{ctx});
  }
};
// Writing MetadataGetter for method: System::Resources::ResourceManager::OnDeserialized
// Il2CppName: OnDeserialized
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (System::Resources::ResourceManager::*)(::System::Runtime::Serialization::StreamingContext)>(&System::Resources::ResourceManager::OnDeserialized)> {
  static const MethodInfo* get() {
    static auto* ctx = &::il2cpp_utils::GetClassFromName("System.Runtime.Serialization", "StreamingContext")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(System::Resources::ResourceManager*), "OnDeserialized", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{ctx});
  }
};
// Writing MetadataGetter for method: System::Resources::ResourceManager::OnSerializing
// Il2CppName: OnSerializing
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (System::Resources::ResourceManager::*)(::System::Runtime::Serialization::StreamingContext)>(&System::Resources::ResourceManager::OnSerializing)> {
  static const MethodInfo* get() {
    static auto* ctx = &::il2cpp_utils::GetClassFromName("System.Runtime.Serialization", "StreamingContext")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(System::Resources::ResourceManager*), "OnSerializing", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{ctx});
  }
};
// Writing MetadataGetter for method: System::Resources::ResourceManager::CommonAssemblyInit
// Il2CppName: CommonAssemblyInit
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (System::Resources::ResourceManager::*)()>(&System::Resources::ResourceManager::CommonAssemblyInit)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(System::Resources::ResourceManager*), "CommonAssemblyInit", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: System::Resources::ResourceManager::get_BaseName
// Il2CppName: get_BaseName
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<::StringW (System::Resources::ResourceManager::*)()>(&System::Resources::ResourceManager::get_BaseName)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(System::Resources::ResourceManager*), "get_BaseName", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: System::Resources::ResourceManager::get_IgnoreCase
// Il2CppName: get_IgnoreCase
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<bool (System::Resources::ResourceManager::*)()>(&System::Resources::ResourceManager::get_IgnoreCase)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(System::Resources::ResourceManager*), "get_IgnoreCase", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: System::Resources::ResourceManager::get_FallbackLocation
// Il2CppName: get_FallbackLocation
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<::System::Resources::UltimateResourceFallbackLocation (System::Resources::ResourceManager::*)()>(&System::Resources::ResourceManager::get_FallbackLocation)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(System::Resources::ResourceManager*), "get_FallbackLocation", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: System::Resources::ResourceManager::GetResourceFileName
// Il2CppName: GetResourceFileName
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<::StringW (System::Resources::ResourceManager::*)(::System::Globalization::CultureInfo*)>(&System::Resources::ResourceManager::GetResourceFileName)> {
  static const MethodInfo* get() {
    static auto* culture = &::il2cpp_utils::GetClassFromName("System.Globalization", "CultureInfo")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(System::Resources::ResourceManager*), "GetResourceFileName", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{culture});
  }
};
// Writing MetadataGetter for method: System::Resources::ResourceManager::GetFirstResourceSet
// Il2CppName: GetFirstResourceSet
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<::System::Resources::ResourceSet* (System::Resources::ResourceManager::*)(::System::Globalization::CultureInfo*)>(&System::Resources::ResourceManager::GetFirstResourceSet)> {
  static const MethodInfo* get() {
    static auto* culture = &::il2cpp_utils::GetClassFromName("System.Globalization", "CultureInfo")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(System::Resources::ResourceManager*), "GetFirstResourceSet", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{culture});
  }
};
// Writing MetadataGetter for method: System::Resources::ResourceManager::GetResourceSet
// Il2CppName: GetResourceSet
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<::System::Resources::ResourceSet* (System::Resources::ResourceManager::*)(::System::Globalization::CultureInfo*, bool, bool)>(&System::Resources::ResourceManager::GetResourceSet)> {
  static const MethodInfo* get() {
    static auto* culture = &::il2cpp_utils::GetClassFromName("System.Globalization", "CultureInfo")->byval_arg;
    static auto* createIfNotExists = &::il2cpp_utils::GetClassFromName("System", "Boolean")->byval_arg;
    static auto* tryParents = &::il2cpp_utils::GetClassFromName("System", "Boolean")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(System::Resources::ResourceManager*), "GetResourceSet", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{culture, createIfNotExists, tryParents});
  }
};
// Writing MetadataGetter for method: System::Resources::ResourceManager::InternalGetResourceSet
// Il2CppName: InternalGetResourceSet
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<::System::Resources::ResourceSet* (System::Resources::ResourceManager::*)(::System::Globalization::CultureInfo*, bool, bool)>(&System::Resources::ResourceManager::InternalGetResourceSet)> {
  static const MethodInfo* get() {
    static auto* culture = &::il2cpp_utils::GetClassFromName("System.Globalization", "CultureInfo")->byval_arg;
    static auto* createIfNotExists = &::il2cpp_utils::GetClassFromName("System", "Boolean")->byval_arg;
    static auto* tryParents = &::il2cpp_utils::GetClassFromName("System", "Boolean")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(System::Resources::ResourceManager*), "InternalGetResourceSet", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{culture, createIfNotExists, tryParents});
  }
};
// Writing MetadataGetter for method: System::Resources::ResourceManager::InternalGetResourceSet
// Il2CppName: InternalGetResourceSet
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<::System::Resources::ResourceSet* (System::Resources::ResourceManager::*)(::System::Globalization::CultureInfo*, bool, bool, ByRef<::System::Threading::StackCrawlMark>)>(&System::Resources::ResourceManager::InternalGetResourceSet)> {
  static const MethodInfo* get() {
    static auto* requestedCulture = &::il2cpp_utils::GetClassFromName("System.Globalization", "CultureInfo")->byval_arg;
    static auto* createIfNotExists = &::il2cpp_utils::GetClassFromName("System", "Boolean")->byval_arg;
    static auto* tryParents = &::il2cpp_utils::GetClassFromName("System", "Boolean")->byval_arg;
    static auto* stackMark = &::il2cpp_utils::GetClassFromName("System.Threading", "StackCrawlMark")->this_arg;
    return ::il2cpp_utils::FindMethod(classof(System::Resources::ResourceManager*), "InternalGetResourceSet", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{requestedCulture, createIfNotExists, tryParents, stackMark});
  }
};
// Writing MetadataGetter for method: System::Resources::ResourceManager::AddResourceSet
// Il2CppName: AddResourceSet
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (*)(::System::Collections::Generic::Dictionary_2<::StringW, ::System::Resources::ResourceSet*>*, ::StringW, ByRef<::System::Resources::ResourceSet*>)>(&System::Resources::ResourceManager::AddResourceSet)> {
  static const MethodInfo* get() {
    static auto* localResourceSets = &::il2cpp_utils::MakeGeneric(::il2cpp_utils::GetClassFromName("System.Collections.Generic", "Dictionary`2"), ::std::vector<const Il2CppClass*>{::il2cpp_utils::GetClassFromName("System", "String"), ::il2cpp_utils::GetClassFromName("System.Resources", "ResourceSet")})->byval_arg;
    static auto* cultureName = &::il2cpp_utils::GetClassFromName("System", "String")->byval_arg;
    static auto* rs = &::il2cpp_utils::GetClassFromName("System.Resources", "ResourceSet")->this_arg;
    return ::il2cpp_utils::FindMethod(classof(System::Resources::ResourceManager*), "AddResourceSet", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{localResourceSets, cultureName, rs});
  }
};
// Writing MetadataGetter for method: System::Resources::ResourceManager::GetSatelliteContractVersion
// Il2CppName: GetSatelliteContractVersion
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<::System::Version* (*)(::System::Reflection::Assembly*)>(&System::Resources::ResourceManager::GetSatelliteContractVersion)> {
  static const MethodInfo* get() {
    static auto* a = &::il2cpp_utils::GetClassFromName("System.Reflection", "Assembly")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(System::Resources::ResourceManager*), "GetSatelliteContractVersion", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{a});
  }
};
// Writing MetadataGetter for method: System::Resources::ResourceManager::GetNeutralResourcesLanguage
// Il2CppName: GetNeutralResourcesLanguage
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<::System::Globalization::CultureInfo* (*)(::System::Reflection::Assembly*)>(&System::Resources::ResourceManager::GetNeutralResourcesLanguage)> {
  static const MethodInfo* get() {
    static auto* a = &::il2cpp_utils::GetClassFromName("System.Reflection", "Assembly")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(System::Resources::ResourceManager*), "GetNeutralResourcesLanguage", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{a});
  }
};
// Writing MetadataGetter for method: System::Resources::ResourceManager::CompareNames
// Il2CppName: CompareNames
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<bool (*)(::StringW, ::StringW, ::System::Reflection::AssemblyName*)>(&System::Resources::ResourceManager::CompareNames)> {
  static const MethodInfo* get() {
    static auto* asmTypeName1 = &::il2cpp_utils::GetClassFromName("System", "String")->byval_arg;
    static auto* typeName2 = &::il2cpp_utils::GetClassFromName("System", "String")->byval_arg;
    static auto* asmName2 = &::il2cpp_utils::GetClassFromName("System.Reflection", "AssemblyName")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(System::Resources::ResourceManager*), "CompareNames", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{asmTypeName1, typeName2, asmName2});
  }
};
// Writing MetadataGetter for method: System::Resources::ResourceManager::SetAppXConfiguration
// Il2CppName: SetAppXConfiguration
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (System::Resources::ResourceManager::*)()>(&System::Resources::ResourceManager::SetAppXConfiguration)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(System::Resources::ResourceManager*), "SetAppXConfiguration", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: System::Resources::ResourceManager::GetString
// Il2CppName: GetString
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<::StringW (System::Resources::ResourceManager::*)(::StringW, ::System::Globalization::CultureInfo*)>(&System::Resources::ResourceManager::GetString)> {
  static const MethodInfo* get() {
    static auto* name = &::il2cpp_utils::GetClassFromName("System", "String")->byval_arg;
    static auto* culture = &::il2cpp_utils::GetClassFromName("System.Globalization", "CultureInfo")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(System::Resources::ResourceManager*), "GetString", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{name, culture});
  }
};
// Writing MetadataGetter for method: System::Resources::ResourceManager::_cctor
// Il2CppName: .cctor
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (*)()>(&System::Resources::ResourceManager::_cctor)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(System::Resources::ResourceManager*), ".cctor", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: System::Resources::ResourceManager::New_ctor
// Il2CppName: .ctor
// Cannot get method pointer of value based method overload from template for constructor!
// Try using FindMethod instead!
