// Autogenerated from CppHeaderCreator
// Created by Sc2ad
// =========================================================================
#pragma once
// Begin includes
#include "beatsaber-hook/shared/utils/typedefs.h"
#include "beatsaber-hook/shared/utils/byref.hpp"
// Including type: Cinemachine.CinemachineVirtualCameraBase
#include "Cinemachine/CinemachineVirtualCameraBase.hpp"
// Including type: Cinemachine.LensSettings
#include "Cinemachine/LensSettings.hpp"
// Including type: Cinemachine.CinemachineVirtualCameraBase/TransitionParams
#include "Cinemachine/CinemachineVirtualCameraBase_TransitionParams.hpp"
// Including type: Cinemachine.CinemachineOrbitalTransposer/Heading
#include "Cinemachine/CinemachineOrbitalTransposer.hpp"
// Including type: Cinemachine.CinemachineTransposer/BindingMode
#include "Cinemachine/CinemachineTransposer.hpp"
// Including type: UnityEngine.Vector4
#include "UnityEngine/Vector4.hpp"
#include "beatsaber-hook/shared/utils/il2cpp-utils-methods.hpp"
#include "beatsaber-hook/shared/utils/il2cpp-utils-properties.hpp"
#include "beatsaber-hook/shared/utils/il2cpp-utils-fields.hpp"
#include "beatsaber-hook/shared/utils/utils.h"
#include "beatsaber-hook/shared/utils/typedefs-array.hpp"
#include "beatsaber-hook/shared/utils/typedefs-string.hpp"
// Completed includes
// Begin forward declares
// Forward declaring namespace: Cinemachine
namespace Cinemachine {
  // Forward declaring type: CinemachineVirtualCamera
  class CinemachineVirtualCamera;
  // Skipping declaration: CinemachineOrbitalTransposer because it is already included!
  // Forward declaring type: CinemachineBlend
  class CinemachineBlend;
  // Skipping declaration: ICinemachineCamera because it is already included!
}
// Forward declaring namespace: UnityEngine
namespace UnityEngine {
  // Forward declaring type: Transform
  class Transform;
  // Skipping declaration: Vector3 because it is already included!
  // Skipping declaration: Quaternion because it is already included!
}
// Completed forward declares
// Type namespace: Cinemachine
namespace Cinemachine {
  // Forward declaring type: CinemachineFreeLook
  class CinemachineFreeLook;
}
#include "beatsaber-hook/shared/utils/il2cpp-type-check.hpp"
NEED_NO_BOX(::Cinemachine::CinemachineFreeLook);
DEFINE_IL2CPP_ARG_TYPE(::Cinemachine::CinemachineFreeLook*, "Cinemachine", "CinemachineFreeLook");
// Type namespace: Cinemachine
namespace Cinemachine {
  // Size: 0x330
  #pragma pack(push, 1)
  // Autogenerated type: Cinemachine.CinemachineFreeLook
  // [TokenAttribute] Offset: FFFFFFFF
  // [DocumentationSortingAttribute] Offset: AE5590
  // [DisallowMultipleComponent] Offset: FFFFFFFF
  // [ExecuteAlways] Offset: FFFFFFFF
  // [ExcludeFromPresetAttribute] Offset: FFFFFFFF
  // [AddComponentMenu] Offset: AE5590
  // [HelpURLAttribute] Offset: AE5590
  class CinemachineFreeLook : public ::Cinemachine::CinemachineVirtualCameraBase {
    public:
    // Writing base type padding for base size: 0x64 to desired offset: 0x68
    char ___base_padding[0x4] = {};
    // Nested type: ::Cinemachine::CinemachineFreeLook::Orbit
    struct Orbit;
    // Nested type: ::Cinemachine::CinemachineFreeLook::CreateRigDelegate
    class CreateRigDelegate;
    // Nested type: ::Cinemachine::CinemachineFreeLook::DestroyRigDelegate
    class DestroyRigDelegate;
    // Size: 0x8
    #pragma pack(push, 1)
    // WARNING Layout: Sequential may not be correctly taken into account!
    // Autogenerated type: Cinemachine.CinemachineFreeLook/Orbit
    // [TokenAttribute] Offset: FFFFFFFF
    struct Orbit/*, public ::System::ValueType*/ {
      public:
      public:
      // public System.Single m_Height
      // Size: 0x4
      // Offset: 0x0
      float m_Height;
      // Field size check
      static_assert(sizeof(float) == 0x4);
      // public System.Single m_Radius
      // Size: 0x4
      // Offset: 0x4
      float m_Radius;
      // Field size check
      static_assert(sizeof(float) == 0x4);
      public:
      // Creating value type constructor for type: Orbit
      constexpr Orbit(float m_Height_ = {}, float m_Radius_ = {}) noexcept : m_Height{m_Height_}, m_Radius{m_Radius_} {}
      // Creating interface conversion operator: operator ::System::ValueType
      operator ::System::ValueType() noexcept {
        return *reinterpret_cast<::System::ValueType*>(this);
      }
      // Get instance field reference: public System.Single m_Height
      [[deprecated("Use field access instead!")]] float& dyn_m_Height();
      // Get instance field reference: public System.Single m_Radius
      [[deprecated("Use field access instead!")]] float& dyn_m_Radius();
      // public System.Void .ctor(System.Single h, System.Single r)
      // Offset: 0x9A5DD4
      // ABORTED: conflicts with another method.  Orbit(float h, float r);
    }; // Cinemachine.CinemachineFreeLook/Orbit
    #pragma pack(pop)
    static check_size<sizeof(CinemachineFreeLook::Orbit), 4 + sizeof(float)> __Cinemachine_CinemachineFreeLook_OrbitSizeCheck;
    static_assert(sizeof(CinemachineFreeLook::Orbit) == 0x8);
    public:
    // [TooltipAttribute] Offset: 0xAE7BA0
    // public UnityEngine.Transform m_LookAt
    // Size: 0x8
    // Offset: 0x68
    ::UnityEngine::Transform* m_LookAt;
    // Field size check
    static_assert(sizeof(::UnityEngine::Transform*) == 0x8);
    // [TooltipAttribute] Offset: 0xAE7BFC
    // public UnityEngine.Transform m_Follow
    // Size: 0x8
    // Offset: 0x70
    ::UnityEngine::Transform* m_Follow;
    // Field size check
    static_assert(sizeof(::UnityEngine::Transform*) == 0x8);
    // [TooltipAttribute] Offset: 0xAE7C58
    // [FormerlySerializedAsAttribute] Offset: 0xAE7C58
    // public System.Boolean m_CommonLens
    // Size: 0x1
    // Offset: 0x78
    bool m_CommonLens;
    // Field size check
    static_assert(sizeof(bool) == 0x1);
    // Padding between fields: m_CommonLens and: m_Lens
    char __padding2[0x3] = {};
    // [FormerlySerializedAsAttribute] Offset: 0xAE7CB8
    // [TooltipAttribute] Offset: 0xAE7CB8
    // public Cinemachine.LensSettings m_Lens
    // Size: 0x2E
    // Offset: 0x7C
    ::Cinemachine::LensSettings m_Lens;
    // Field size check
    static_assert(sizeof(::Cinemachine::LensSettings) == 0x2E);
    // Padding between fields: m_Lens and: m_Transitions
    char __padding3[0x6] = {};
    // public Cinemachine.CinemachineVirtualCameraBase/TransitionParams m_Transitions
    // Size: 0x10
    // Offset: 0xB0
    ::Cinemachine::CinemachineVirtualCameraBase::TransitionParams m_Transitions;
    // Field size check
    static_assert(sizeof(::Cinemachine::CinemachineVirtualCameraBase::TransitionParams) == 0x10);
    // [FormerlySerializedAsAttribute] Offset: 0xAE7D18
    // [FormerlySerializedAsAttribute] Offset: 0xAE7D18
    // private Cinemachine.CinemachineVirtualCameraBase/BlendHint m_LegacyBlendHint
    // Size: 0x4
    // Offset: 0xC0
    ::Cinemachine::CinemachineVirtualCameraBase::BlendHint m_LegacyBlendHint;
    // Field size check
    static_assert(sizeof(::Cinemachine::CinemachineVirtualCameraBase::BlendHint) == 0x4);
    // Padding between fields: m_LegacyBlendHint and: m_YAxis
    char __padding5[0x4] = {};
    // [HeaderAttribute] Offset: 0xAE7D98
    // [TooltipAttribute] Offset: 0xAE7D98
    // public Cinemachine.AxisState m_YAxis
    // Size: 0x66
    // Offset: 0xC8
    ::Cinemachine::AxisState m_YAxis;
    // Field size check
    static_assert(sizeof(::Cinemachine::AxisState) == 0x66);
    // Padding between fields: m_YAxis and: m_YAxisRecentering
    char __padding6[0x2] = {};
    // [TooltipAttribute] Offset: 0xAE7E08
    // public Cinemachine.AxisState/Recentering m_YAxisRecentering
    // Size: 0x1C
    // Offset: 0x130
    ::Cinemachine::AxisState::Recentering m_YAxisRecentering;
    // Field size check
    static_assert(sizeof(::Cinemachine::AxisState::Recentering) == 0x1C);
    // Padding between fields: m_YAxisRecentering and: m_XAxis
    char __padding7[0x4] = {};
    // [TooltipAttribute] Offset: 0xAE7E40
    // public Cinemachine.AxisState m_XAxis
    // Size: 0x66
    // Offset: 0x150
    ::Cinemachine::AxisState m_XAxis;
    // Field size check
    static_assert(sizeof(::Cinemachine::AxisState) == 0x66);
    // Padding between fields: m_XAxis and: m_Heading
    char __padding8[0x2] = {};
    // [TooltipAttribute] Offset: 0xAE7E8C
    // public Cinemachine.CinemachineOrbitalTransposer/Heading m_Heading
    // Size: 0xC
    // Offset: 0x1B8
    ::Cinemachine::CinemachineOrbitalTransposer::Heading m_Heading;
    // Field size check
    static_assert(sizeof(::Cinemachine::CinemachineOrbitalTransposer::Heading) == 0xC);
    // [TooltipAttribute] Offset: 0xAE7ED8
    // public Cinemachine.AxisState/Recentering m_RecenterToTargetHeading
    // Size: 0x1C
    // Offset: 0x1C4
    ::Cinemachine::AxisState::Recentering m_RecenterToTargetHeading;
    // Field size check
    static_assert(sizeof(::Cinemachine::AxisState::Recentering) == 0x1C);
    // [HeaderAttribute] Offset: 0xAE7F10
    // [TooltipAttribute] Offset: 0xAE7F10
    // public Cinemachine.CinemachineTransposer/BindingMode m_BindingMode
    // Size: 0x4
    // Offset: 0x1E0
    ::Cinemachine::CinemachineTransposer::BindingMode m_BindingMode;
    // Field size check
    static_assert(sizeof(::Cinemachine::CinemachineTransposer::BindingMode) == 0x4);
    // [TooltipAttribute] Offset: 0xAE7F70
    // [RangeAttribute] Offset: 0xAE7F70
    // [FormerlySerializedAsAttribute] Offset: 0xAE7F70
    // public System.Single m_SplineCurvature
    // Size: 0x4
    // Offset: 0x1E4
    float m_SplineCurvature;
    // Field size check
    static_assert(sizeof(float) == 0x4);
    // [TooltipAttribute] Offset: 0xAE7FE8
    // public Cinemachine.CinemachineFreeLook/Orbit[] m_Orbits
    // Size: 0x8
    // Offset: 0x1E8
    ::ArrayW<::Cinemachine::CinemachineFreeLook::Orbit> m_Orbits;
    // Field size check
    static_assert(sizeof(::ArrayW<::Cinemachine::CinemachineFreeLook::Orbit>) == 0x8);
    // [FormerlySerializedAsAttribute] Offset: 0xAE8020
    // private System.Single m_LegacyHeadingBias
    // Size: 0x4
    // Offset: 0x1F0
    float m_LegacyHeadingBias;
    // Field size check
    static_assert(sizeof(float) == 0x4);
    // private System.Boolean mUseLegacyRigDefinitions
    // Size: 0x1
    // Offset: 0x1F4
    bool mUseLegacyRigDefinitions;
    // Field size check
    static_assert(sizeof(bool) == 0x1);
    // private System.Boolean mIsDestroyed
    // Size: 0x1
    // Offset: 0x1F5
    bool mIsDestroyed;
    // Field size check
    static_assert(sizeof(bool) == 0x1);
    // Padding between fields: mIsDestroyed and: m_State
    char __padding16[0x2] = {};
    // private Cinemachine.CameraState m_State
    // Size: 0xE4
    // Offset: 0x1F8
    ::Cinemachine::CameraState m_State;
    // Field size check
    static_assert(sizeof(::Cinemachine::CameraState) == 0xE4);
    // Padding between fields: m_State and: m_Rigs
    char __padding17[0x4] = {};
    // private Cinemachine.CinemachineVirtualCamera[] m_Rigs
    // Size: 0x8
    // Offset: 0x2E0
    ::ArrayW<::Cinemachine::CinemachineVirtualCamera*> m_Rigs;
    // Field size check
    static_assert(sizeof(::ArrayW<::Cinemachine::CinemachineVirtualCamera*>) == 0x8);
    // private Cinemachine.CinemachineOrbitalTransposer[] mOrbitals
    // Size: 0x8
    // Offset: 0x2E8
    ::ArrayW<::Cinemachine::CinemachineOrbitalTransposer*> mOrbitals;
    // Field size check
    static_assert(sizeof(::ArrayW<::Cinemachine::CinemachineOrbitalTransposer*>) == 0x8);
    // private Cinemachine.CinemachineBlend mBlendA
    // Size: 0x8
    // Offset: 0x2F0
    ::Cinemachine::CinemachineBlend* mBlendA;
    // Field size check
    static_assert(sizeof(::Cinemachine::CinemachineBlend*) == 0x8);
    // private Cinemachine.CinemachineBlend mBlendB
    // Size: 0x8
    // Offset: 0x2F8
    ::Cinemachine::CinemachineBlend* mBlendB;
    // Field size check
    static_assert(sizeof(::Cinemachine::CinemachineBlend*) == 0x8);
    // [CompilerGeneratedAttribute] Offset: 0xAE80C4
    // private System.Single <CachedXAxisHeading>k__BackingField
    // Size: 0x4
    // Offset: 0x300
    float CachedXAxisHeading;
    // Field size check
    static_assert(sizeof(float) == 0x4);
    // Padding between fields: CachedXAxisHeading and: m_CachedOrbits
    char __padding22[0x4] = {};
    // private Cinemachine.CinemachineFreeLook/Orbit[] m_CachedOrbits
    // Size: 0x8
    // Offset: 0x308
    ::ArrayW<::Cinemachine::CinemachineFreeLook::Orbit> m_CachedOrbits;
    // Field size check
    static_assert(sizeof(::ArrayW<::Cinemachine::CinemachineFreeLook::Orbit>) == 0x8);
    // private System.Single m_CachedTension
    // Size: 0x4
    // Offset: 0x310
    float m_CachedTension;
    // Field size check
    static_assert(sizeof(float) == 0x4);
    // Padding between fields: m_CachedTension and: m_CachedKnots
    char __padding24[0x4] = {};
    // private UnityEngine.Vector4[] m_CachedKnots
    // Size: 0x8
    // Offset: 0x318
    ::ArrayW<::UnityEngine::Vector4> m_CachedKnots;
    // Field size check
    static_assert(sizeof(::ArrayW<::UnityEngine::Vector4>) == 0x8);
    // private UnityEngine.Vector4[] m_CachedCtrl1
    // Size: 0x8
    // Offset: 0x320
    ::ArrayW<::UnityEngine::Vector4> m_CachedCtrl1;
    // Field size check
    static_assert(sizeof(::ArrayW<::UnityEngine::Vector4>) == 0x8);
    // private UnityEngine.Vector4[] m_CachedCtrl2
    // Size: 0x8
    // Offset: 0x328
    ::ArrayW<::UnityEngine::Vector4> m_CachedCtrl2;
    // Field size check
    static_assert(sizeof(::ArrayW<::UnityEngine::Vector4>) == 0x8);
    public:
    // Get static field: static public Cinemachine.CinemachineFreeLook/CreateRigDelegate CreateRigOverride
    static ::Cinemachine::CinemachineFreeLook::CreateRigDelegate* _get_CreateRigOverride();
    // Set static field: static public Cinemachine.CinemachineFreeLook/CreateRigDelegate CreateRigOverride
    static void _set_CreateRigOverride(::Cinemachine::CinemachineFreeLook::CreateRigDelegate* value);
    // Get static field: static public Cinemachine.CinemachineFreeLook/DestroyRigDelegate DestroyRigOverride
    static ::Cinemachine::CinemachineFreeLook::DestroyRigDelegate* _get_DestroyRigOverride();
    // Set static field: static public Cinemachine.CinemachineFreeLook/DestroyRigDelegate DestroyRigOverride
    static void _set_DestroyRigOverride(::Cinemachine::CinemachineFreeLook::DestroyRigDelegate* value);
    // Get instance field reference: public UnityEngine.Transform m_LookAt
    [[deprecated("Use field access instead!")]] ::UnityEngine::Transform*& dyn_m_LookAt();
    // Get instance field reference: public UnityEngine.Transform m_Follow
    [[deprecated("Use field access instead!")]] ::UnityEngine::Transform*& dyn_m_Follow();
    // Get instance field reference: public System.Boolean m_CommonLens
    [[deprecated("Use field access instead!")]] bool& dyn_m_CommonLens();
    // Get instance field reference: public Cinemachine.LensSettings m_Lens
    [[deprecated("Use field access instead!")]] ::Cinemachine::LensSettings& dyn_m_Lens();
    // Get instance field reference: public Cinemachine.CinemachineVirtualCameraBase/TransitionParams m_Transitions
    [[deprecated("Use field access instead!")]] ::Cinemachine::CinemachineVirtualCameraBase::TransitionParams& dyn_m_Transitions();
    // Get instance field reference: private Cinemachine.CinemachineVirtualCameraBase/BlendHint m_LegacyBlendHint
    [[deprecated("Use field access instead!")]] ::Cinemachine::CinemachineVirtualCameraBase::BlendHint& dyn_m_LegacyBlendHint();
    // Get instance field reference: public Cinemachine.AxisState m_YAxis
    [[deprecated("Use field access instead!")]] ::Cinemachine::AxisState& dyn_m_YAxis();
    // Get instance field reference: public Cinemachine.AxisState/Recentering m_YAxisRecentering
    [[deprecated("Use field access instead!")]] ::Cinemachine::AxisState::Recentering& dyn_m_YAxisRecentering();
    // Get instance field reference: public Cinemachine.AxisState m_XAxis
    [[deprecated("Use field access instead!")]] ::Cinemachine::AxisState& dyn_m_XAxis();
    // Get instance field reference: public Cinemachine.CinemachineOrbitalTransposer/Heading m_Heading
    [[deprecated("Use field access instead!")]] ::Cinemachine::CinemachineOrbitalTransposer::Heading& dyn_m_Heading();
    // Get instance field reference: public Cinemachine.AxisState/Recentering m_RecenterToTargetHeading
    [[deprecated("Use field access instead!")]] ::Cinemachine::AxisState::Recentering& dyn_m_RecenterToTargetHeading();
    // Get instance field reference: public Cinemachine.CinemachineTransposer/BindingMode m_BindingMode
    [[deprecated("Use field access instead!")]] ::Cinemachine::CinemachineTransposer::BindingMode& dyn_m_BindingMode();
    // Get instance field reference: public System.Single m_SplineCurvature
    [[deprecated("Use field access instead!")]] float& dyn_m_SplineCurvature();
    // Get instance field reference: public Cinemachine.CinemachineFreeLook/Orbit[] m_Orbits
    [[deprecated("Use field access instead!")]] ::ArrayW<::Cinemachine::CinemachineFreeLook::Orbit>& dyn_m_Orbits();
    // Get instance field reference: private System.Single m_LegacyHeadingBias
    [[deprecated("Use field access instead!")]] float& dyn_m_LegacyHeadingBias();
    // Get instance field reference: private System.Boolean mUseLegacyRigDefinitions
    [[deprecated("Use field access instead!")]] bool& dyn_mUseLegacyRigDefinitions();
    // Get instance field reference: private System.Boolean mIsDestroyed
    [[deprecated("Use field access instead!")]] bool& dyn_mIsDestroyed();
    // Get instance field reference: private Cinemachine.CameraState m_State
    [[deprecated("Use field access instead!")]] ::Cinemachine::CameraState& dyn_m_State();
    // Get instance field reference: private Cinemachine.CinemachineVirtualCamera[] m_Rigs
    [[deprecated("Use field access instead!")]] ::ArrayW<::Cinemachine::CinemachineVirtualCamera*>& dyn_m_Rigs();
    // Get instance field reference: private Cinemachine.CinemachineOrbitalTransposer[] mOrbitals
    [[deprecated("Use field access instead!")]] ::ArrayW<::Cinemachine::CinemachineOrbitalTransposer*>& dyn_mOrbitals();
    // Get instance field reference: private Cinemachine.CinemachineBlend mBlendA
    [[deprecated("Use field access instead!")]] ::Cinemachine::CinemachineBlend*& dyn_mBlendA();
    // Get instance field reference: private Cinemachine.CinemachineBlend mBlendB
    [[deprecated("Use field access instead!")]] ::Cinemachine::CinemachineBlend*& dyn_mBlendB();
    // Get instance field reference: private System.Single <CachedXAxisHeading>k__BackingField
    [[deprecated("Use field access instead!")]] float& dyn_$CachedXAxisHeading$k__BackingField();
    // Get instance field reference: private Cinemachine.CinemachineFreeLook/Orbit[] m_CachedOrbits
    [[deprecated("Use field access instead!")]] ::ArrayW<::Cinemachine::CinemachineFreeLook::Orbit>& dyn_m_CachedOrbits();
    // Get instance field reference: private System.Single m_CachedTension
    [[deprecated("Use field access instead!")]] float& dyn_m_CachedTension();
    // Get instance field reference: private UnityEngine.Vector4[] m_CachedKnots
    [[deprecated("Use field access instead!")]] ::ArrayW<::UnityEngine::Vector4>& dyn_m_CachedKnots();
    // Get instance field reference: private UnityEngine.Vector4[] m_CachedCtrl1
    [[deprecated("Use field access instead!")]] ::ArrayW<::UnityEngine::Vector4>& dyn_m_CachedCtrl1();
    // Get instance field reference: private UnityEngine.Vector4[] m_CachedCtrl2
    [[deprecated("Use field access instead!")]] ::ArrayW<::UnityEngine::Vector4>& dyn_m_CachedCtrl2();
    // public Cinemachine.CinemachineVirtualCamera GetRig(System.Int32 i)
    // Offset: 0xFC316C
    ::Cinemachine::CinemachineVirtualCamera* GetRig(int i);
    // static public System.String[] get_RigNames()
    // Offset: 0xFC339C
    static ::ArrayW<::StringW> get_RigNames();
    // public System.Void UpdateInputAxisProvider()
    // Offset: 0xFC34DC
    void UpdateInputAxisProvider();
    // private System.Void OnTransformChildrenChanged()
    // Offset: 0xFC36D0
    void OnTransformChildrenChanged();
    // private System.Void Reset()
    // Offset: 0xFC36D8
    void Reset();
    // private System.Single GetYAxisClosestValue(UnityEngine.Vector3 cameraPos, UnityEngine.Vector3 up)
    // Offset: 0xFC4148
    float GetYAxisClosestValue(::UnityEngine::Vector3 cameraPos, ::UnityEngine::Vector3 up);
    // private System.Void InvalidateRigCache()
    // Offset: 0xFC3164
    void InvalidateRigCache();
    // private System.Void DestroyRigs()
    // Offset: 0xFC36DC
    void DestroyRigs();
    // private Cinemachine.CinemachineVirtualCamera[] CreateRigs(Cinemachine.CinemachineVirtualCamera[] copyFrom)
    // Offset: 0xFC5D70
    ::ArrayW<::Cinemachine::CinemachineVirtualCamera*> CreateRigs(::ArrayW<::Cinemachine::CinemachineVirtualCamera*> copyFrom);
    // private System.Void UpdateRigCache()
    // Offset: 0xFC31CC
    void UpdateRigCache();
    // private System.Int32 LocateExistingRigs(System.String[] rigNames, System.Boolean forceOrbital)
    // Offset: 0xFC65C4
    int LocateExistingRigs(::ArrayW<::StringW> rigNames, bool forceOrbital);
    // private System.Single get_CachedXAxisHeading()
    // Offset: 0xFC6DB8
    float get_CachedXAxisHeading();
    // private System.Void set_CachedXAxisHeading(System.Single value)
    // Offset: 0xFC6DC0
    void set_CachedXAxisHeading(float value);
    // private System.Single UpdateXAxisHeading(Cinemachine.CinemachineOrbitalTransposer orbital, System.Single deltaTime, UnityEngine.Vector3 up)
    // Offset: 0xFC6DC8
    float UpdateXAxisHeading(::Cinemachine::CinemachineOrbitalTransposer* orbital, float deltaTime, ::UnityEngine::Vector3 up);
    // private System.Void PushSettingsToRigs()
    // Offset: 0xFC48F8
    void PushSettingsToRigs();
    // private System.Single GetYAxisValue()
    // Offset: 0xFC3E18
    float GetYAxisValue();
    // private Cinemachine.CameraState CalculateNewState(UnityEngine.Vector3 worldUp, System.Single deltaTime)
    // Offset: 0xFC51B0
    ::Cinemachine::CameraState CalculateNewState(::UnityEngine::Vector3 worldUp, float deltaTime);
    // public UnityEngine.Vector3 GetLocalPositionForCameraFromInput(System.Single t)
    // Offset: 0xFC57A0
    ::UnityEngine::Vector3 GetLocalPositionForCameraFromInput(float t);
    // private System.Void UpdateCachedSpline()
    // Offset: 0xFC70AC
    void UpdateCachedSpline();
    // protected override System.Void OnValidate()
    // Offset: 0xFC309C
    // Implemented from: Cinemachine.CinemachineVirtualCameraBase
    // Base method: System.Void CinemachineVirtualCameraBase::OnValidate()
    void OnValidate();
    // protected override System.Void OnEnable()
    // Offset: 0xFC34AC
    // Implemented from: Cinemachine.CinemachineVirtualCameraBase
    // Base method: System.Void CinemachineVirtualCameraBase::OnEnable()
    void OnEnable();
    // protected override System.Void OnDestroy()
    // Offset: 0xFC3578
    // Implemented from: Cinemachine.CinemachineVirtualCameraBase
    // Base method: System.Void CinemachineVirtualCameraBase::OnDestroy()
    void OnDestroy();
    // public override System.Boolean get_PreviousStateIsValid()
    // Offset: 0xFC3BD8
    // Implemented from: Cinemachine.CinemachineVirtualCameraBase
    // Base method: System.Boolean CinemachineVirtualCameraBase::get_PreviousStateIsValid()
    bool get_PreviousStateIsValid();
    // public override System.Void set_PreviousStateIsValid(System.Boolean value)
    // Offset: 0xFC3BE0
    // Implemented from: Cinemachine.CinemachineVirtualCameraBase
    // Base method: System.Void CinemachineVirtualCameraBase::set_PreviousStateIsValid(System.Boolean value)
    void set_PreviousStateIsValid(bool value);
    // public override Cinemachine.CameraState get_State()
    // Offset: 0xFC3CE8
    // Implemented from: Cinemachine.CinemachineVirtualCameraBase
    // Base method: Cinemachine.CameraState CinemachineVirtualCameraBase::get_State()
    ::Cinemachine::CameraState get_State();
    // public override UnityEngine.Transform get_LookAt()
    // Offset: 0xFC3CF8
    // Implemented from: Cinemachine.CinemachineVirtualCameraBase
    // Base method: UnityEngine.Transform CinemachineVirtualCameraBase::get_LookAt()
    ::UnityEngine::Transform* get_LookAt();
    // public override System.Void set_LookAt(UnityEngine.Transform value)
    // Offset: 0xFC3D04
    // Implemented from: Cinemachine.CinemachineVirtualCameraBase
    // Base method: System.Void CinemachineVirtualCameraBase::set_LookAt(UnityEngine.Transform value)
    void set_LookAt(::UnityEngine::Transform* value);
    // public override UnityEngine.Transform get_Follow()
    // Offset: 0xFC3D0C
    // Implemented from: Cinemachine.CinemachineVirtualCameraBase
    // Base method: UnityEngine.Transform CinemachineVirtualCameraBase::get_Follow()
    ::UnityEngine::Transform* get_Follow();
    // public override System.Void set_Follow(UnityEngine.Transform value)
    // Offset: 0xFC3D18
    // Implemented from: Cinemachine.CinemachineVirtualCameraBase
    // Base method: System.Void CinemachineVirtualCameraBase::set_Follow(UnityEngine.Transform value)
    void set_Follow(::UnityEngine::Transform* value);
    // public override System.Boolean IsLiveChild(Cinemachine.ICinemachineCamera vcam, System.Boolean dominantChildOnly)
    // Offset: 0xFC3D20
    // Implemented from: Cinemachine.CinemachineVirtualCameraBase
    // Base method: System.Boolean CinemachineVirtualCameraBase::IsLiveChild(Cinemachine.ICinemachineCamera vcam, System.Boolean dominantChildOnly)
    bool IsLiveChild(::Cinemachine::ICinemachineCamera* vcam, bool dominantChildOnly);
    // public override System.Void OnTargetObjectWarped(UnityEngine.Transform target, UnityEngine.Vector3 positionDelta)
    // Offset: 0xFC3E44
    // Implemented from: Cinemachine.CinemachineVirtualCameraBase
    // Base method: System.Void CinemachineVirtualCameraBase::OnTargetObjectWarped(UnityEngine.Transform target, UnityEngine.Vector3 positionDelta)
    void OnTargetObjectWarped(::UnityEngine::Transform* target, ::UnityEngine::Vector3 positionDelta);
    // public override System.Void ForceCameraPosition(UnityEngine.Vector3 pos, UnityEngine.Quaternion rot)
    // Offset: 0xFC3F18
    // Implemented from: Cinemachine.CinemachineVirtualCameraBase
    // Base method: System.Void CinemachineVirtualCameraBase::ForceCameraPosition(UnityEngine.Vector3 pos, UnityEngine.Quaternion rot)
    void ForceCameraPosition(::UnityEngine::Vector3 pos, ::UnityEngine::Quaternion rot);
    // public override System.Void InternalUpdateCameraState(UnityEngine.Vector3 worldUp, System.Single deltaTime)
    // Offset: 0xFC4DF8
    // Implemented from: Cinemachine.CinemachineVirtualCameraBase
    // Base method: System.Void CinemachineVirtualCameraBase::InternalUpdateCameraState(UnityEngine.Vector3 worldUp, System.Single deltaTime)
    void InternalUpdateCameraState(::UnityEngine::Vector3 worldUp, float deltaTime);
    // public override System.Void OnTransitionFromCamera(Cinemachine.ICinemachineCamera fromCam, UnityEngine.Vector3 worldUp, System.Single deltaTime)
    // Offset: 0xFC533C
    // Implemented from: Cinemachine.CinemachineVirtualCameraBase
    // Base method: System.Void CinemachineVirtualCameraBase::OnTransitionFromCamera(Cinemachine.ICinemachineCamera fromCam, UnityEngine.Vector3 worldUp, System.Single deltaTime)
    void OnTransitionFromCamera(::Cinemachine::ICinemachineCamera* fromCam, ::UnityEngine::Vector3 worldUp, float deltaTime);
    // public System.Void .ctor()
    // Offset: 0xFC7444
    // Implemented from: Cinemachine.CinemachineVirtualCameraBase
    // Base method: System.Void CinemachineVirtualCameraBase::.ctor()
    template<::il2cpp_utils::CreationType creationType = ::il2cpp_utils::CreationType::Temporary>
    static CinemachineFreeLook* New_ctor() {
      static auto ___internal__logger = ::Logger::get().WithContext("::Cinemachine::CinemachineFreeLook::.ctor");
      return THROW_UNLESS((::il2cpp_utils::New<CinemachineFreeLook*, creationType>()));
    }
  }; // Cinemachine.CinemachineFreeLook
  #pragma pack(pop)
  static check_size<sizeof(CinemachineFreeLook), 808 + sizeof(::ArrayW<::UnityEngine::Vector4>)> __Cinemachine_CinemachineFreeLookSizeCheck;
  static_assert(sizeof(CinemachineFreeLook) == 0x330);
}
#include "beatsaber-hook/shared/utils/il2cpp-type-check.hpp"
DEFINE_IL2CPP_ARG_TYPE(::Cinemachine::CinemachineFreeLook::Orbit, "Cinemachine", "CinemachineFreeLook/Orbit");
#include "beatsaber-hook/shared/utils/il2cpp-utils-methods.hpp"
// Writing MetadataGetter for method: Cinemachine::CinemachineFreeLook::GetRig
// Il2CppName: GetRig
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<::Cinemachine::CinemachineVirtualCamera* (Cinemachine::CinemachineFreeLook::*)(int)>(&Cinemachine::CinemachineFreeLook::GetRig)> {
  static const MethodInfo* get() {
    static auto* i = &::il2cpp_utils::GetClassFromName("System", "Int32")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(Cinemachine::CinemachineFreeLook*), "GetRig", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{i});
  }
};
// Writing MetadataGetter for method: Cinemachine::CinemachineFreeLook::get_RigNames
// Il2CppName: get_RigNames
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<::ArrayW<::StringW> (*)()>(&Cinemachine::CinemachineFreeLook::get_RigNames)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(Cinemachine::CinemachineFreeLook*), "get_RigNames", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: Cinemachine::CinemachineFreeLook::UpdateInputAxisProvider
// Il2CppName: UpdateInputAxisProvider
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (Cinemachine::CinemachineFreeLook::*)()>(&Cinemachine::CinemachineFreeLook::UpdateInputAxisProvider)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(Cinemachine::CinemachineFreeLook*), "UpdateInputAxisProvider", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: Cinemachine::CinemachineFreeLook::OnTransformChildrenChanged
// Il2CppName: OnTransformChildrenChanged
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (Cinemachine::CinemachineFreeLook::*)()>(&Cinemachine::CinemachineFreeLook::OnTransformChildrenChanged)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(Cinemachine::CinemachineFreeLook*), "OnTransformChildrenChanged", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: Cinemachine::CinemachineFreeLook::Reset
// Il2CppName: Reset
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (Cinemachine::CinemachineFreeLook::*)()>(&Cinemachine::CinemachineFreeLook::Reset)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(Cinemachine::CinemachineFreeLook*), "Reset", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: Cinemachine::CinemachineFreeLook::GetYAxisClosestValue
// Il2CppName: GetYAxisClosestValue
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<float (Cinemachine::CinemachineFreeLook::*)(::UnityEngine::Vector3, ::UnityEngine::Vector3)>(&Cinemachine::CinemachineFreeLook::GetYAxisClosestValue)> {
  static const MethodInfo* get() {
    static auto* cameraPos = &::il2cpp_utils::GetClassFromName("UnityEngine", "Vector3")->byval_arg;
    static auto* up = &::il2cpp_utils::GetClassFromName("UnityEngine", "Vector3")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(Cinemachine::CinemachineFreeLook*), "GetYAxisClosestValue", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{cameraPos, up});
  }
};
// Writing MetadataGetter for method: Cinemachine::CinemachineFreeLook::InvalidateRigCache
// Il2CppName: InvalidateRigCache
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (Cinemachine::CinemachineFreeLook::*)()>(&Cinemachine::CinemachineFreeLook::InvalidateRigCache)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(Cinemachine::CinemachineFreeLook*), "InvalidateRigCache", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: Cinemachine::CinemachineFreeLook::DestroyRigs
// Il2CppName: DestroyRigs
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (Cinemachine::CinemachineFreeLook::*)()>(&Cinemachine::CinemachineFreeLook::DestroyRigs)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(Cinemachine::CinemachineFreeLook*), "DestroyRigs", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: Cinemachine::CinemachineFreeLook::CreateRigs
// Il2CppName: CreateRigs
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<::ArrayW<::Cinemachine::CinemachineVirtualCamera*> (Cinemachine::CinemachineFreeLook::*)(::ArrayW<::Cinemachine::CinemachineVirtualCamera*>)>(&Cinemachine::CinemachineFreeLook::CreateRigs)> {
  static const MethodInfo* get() {
    static auto* copyFrom = &il2cpp_functions::array_class_get(::il2cpp_utils::GetClassFromName("Cinemachine", "CinemachineVirtualCamera"), 1)->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(Cinemachine::CinemachineFreeLook*), "CreateRigs", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{copyFrom});
  }
};
// Writing MetadataGetter for method: Cinemachine::CinemachineFreeLook::UpdateRigCache
// Il2CppName: UpdateRigCache
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (Cinemachine::CinemachineFreeLook::*)()>(&Cinemachine::CinemachineFreeLook::UpdateRigCache)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(Cinemachine::CinemachineFreeLook*), "UpdateRigCache", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: Cinemachine::CinemachineFreeLook::LocateExistingRigs
// Il2CppName: LocateExistingRigs
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<int (Cinemachine::CinemachineFreeLook::*)(::ArrayW<::StringW>, bool)>(&Cinemachine::CinemachineFreeLook::LocateExistingRigs)> {
  static const MethodInfo* get() {
    static auto* rigNames = &il2cpp_functions::array_class_get(::il2cpp_utils::GetClassFromName("System", "String"), 1)->byval_arg;
    static auto* forceOrbital = &::il2cpp_utils::GetClassFromName("System", "Boolean")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(Cinemachine::CinemachineFreeLook*), "LocateExistingRigs", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{rigNames, forceOrbital});
  }
};
// Writing MetadataGetter for method: Cinemachine::CinemachineFreeLook::get_CachedXAxisHeading
// Il2CppName: get_CachedXAxisHeading
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<float (Cinemachine::CinemachineFreeLook::*)()>(&Cinemachine::CinemachineFreeLook::get_CachedXAxisHeading)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(Cinemachine::CinemachineFreeLook*), "get_CachedXAxisHeading", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: Cinemachine::CinemachineFreeLook::set_CachedXAxisHeading
// Il2CppName: set_CachedXAxisHeading
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (Cinemachine::CinemachineFreeLook::*)(float)>(&Cinemachine::CinemachineFreeLook::set_CachedXAxisHeading)> {
  static const MethodInfo* get() {
    static auto* value = &::il2cpp_utils::GetClassFromName("System", "Single")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(Cinemachine::CinemachineFreeLook*), "set_CachedXAxisHeading", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{value});
  }
};
// Writing MetadataGetter for method: Cinemachine::CinemachineFreeLook::UpdateXAxisHeading
// Il2CppName: UpdateXAxisHeading
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<float (Cinemachine::CinemachineFreeLook::*)(::Cinemachine::CinemachineOrbitalTransposer*, float, ::UnityEngine::Vector3)>(&Cinemachine::CinemachineFreeLook::UpdateXAxisHeading)> {
  static const MethodInfo* get() {
    static auto* orbital = &::il2cpp_utils::GetClassFromName("Cinemachine", "CinemachineOrbitalTransposer")->byval_arg;
    static auto* deltaTime = &::il2cpp_utils::GetClassFromName("System", "Single")->byval_arg;
    static auto* up = &::il2cpp_utils::GetClassFromName("UnityEngine", "Vector3")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(Cinemachine::CinemachineFreeLook*), "UpdateXAxisHeading", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{orbital, deltaTime, up});
  }
};
// Writing MetadataGetter for method: Cinemachine::CinemachineFreeLook::PushSettingsToRigs
// Il2CppName: PushSettingsToRigs
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (Cinemachine::CinemachineFreeLook::*)()>(&Cinemachine::CinemachineFreeLook::PushSettingsToRigs)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(Cinemachine::CinemachineFreeLook*), "PushSettingsToRigs", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: Cinemachine::CinemachineFreeLook::GetYAxisValue
// Il2CppName: GetYAxisValue
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<float (Cinemachine::CinemachineFreeLook::*)()>(&Cinemachine::CinemachineFreeLook::GetYAxisValue)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(Cinemachine::CinemachineFreeLook*), "GetYAxisValue", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: Cinemachine::CinemachineFreeLook::CalculateNewState
// Il2CppName: CalculateNewState
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<::Cinemachine::CameraState (Cinemachine::CinemachineFreeLook::*)(::UnityEngine::Vector3, float)>(&Cinemachine::CinemachineFreeLook::CalculateNewState)> {
  static const MethodInfo* get() {
    static auto* worldUp = &::il2cpp_utils::GetClassFromName("UnityEngine", "Vector3")->byval_arg;
    static auto* deltaTime = &::il2cpp_utils::GetClassFromName("System", "Single")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(Cinemachine::CinemachineFreeLook*), "CalculateNewState", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{worldUp, deltaTime});
  }
};
// Writing MetadataGetter for method: Cinemachine::CinemachineFreeLook::GetLocalPositionForCameraFromInput
// Il2CppName: GetLocalPositionForCameraFromInput
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<::UnityEngine::Vector3 (Cinemachine::CinemachineFreeLook::*)(float)>(&Cinemachine::CinemachineFreeLook::GetLocalPositionForCameraFromInput)> {
  static const MethodInfo* get() {
    static auto* t = &::il2cpp_utils::GetClassFromName("System", "Single")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(Cinemachine::CinemachineFreeLook*), "GetLocalPositionForCameraFromInput", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{t});
  }
};
// Writing MetadataGetter for method: Cinemachine::CinemachineFreeLook::UpdateCachedSpline
// Il2CppName: UpdateCachedSpline
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (Cinemachine::CinemachineFreeLook::*)()>(&Cinemachine::CinemachineFreeLook::UpdateCachedSpline)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(Cinemachine::CinemachineFreeLook*), "UpdateCachedSpline", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: Cinemachine::CinemachineFreeLook::OnValidate
// Il2CppName: OnValidate
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (Cinemachine::CinemachineFreeLook::*)()>(&Cinemachine::CinemachineFreeLook::OnValidate)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(Cinemachine::CinemachineFreeLook*), "OnValidate", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: Cinemachine::CinemachineFreeLook::OnEnable
// Il2CppName: OnEnable
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (Cinemachine::CinemachineFreeLook::*)()>(&Cinemachine::CinemachineFreeLook::OnEnable)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(Cinemachine::CinemachineFreeLook*), "OnEnable", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: Cinemachine::CinemachineFreeLook::OnDestroy
// Il2CppName: OnDestroy
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (Cinemachine::CinemachineFreeLook::*)()>(&Cinemachine::CinemachineFreeLook::OnDestroy)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(Cinemachine::CinemachineFreeLook*), "OnDestroy", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: Cinemachine::CinemachineFreeLook::get_PreviousStateIsValid
// Il2CppName: get_PreviousStateIsValid
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<bool (Cinemachine::CinemachineFreeLook::*)()>(&Cinemachine::CinemachineFreeLook::get_PreviousStateIsValid)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(Cinemachine::CinemachineFreeLook*), "get_PreviousStateIsValid", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: Cinemachine::CinemachineFreeLook::set_PreviousStateIsValid
// Il2CppName: set_PreviousStateIsValid
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (Cinemachine::CinemachineFreeLook::*)(bool)>(&Cinemachine::CinemachineFreeLook::set_PreviousStateIsValid)> {
  static const MethodInfo* get() {
    static auto* value = &::il2cpp_utils::GetClassFromName("System", "Boolean")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(Cinemachine::CinemachineFreeLook*), "set_PreviousStateIsValid", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{value});
  }
};
// Writing MetadataGetter for method: Cinemachine::CinemachineFreeLook::get_State
// Il2CppName: get_State
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<::Cinemachine::CameraState (Cinemachine::CinemachineFreeLook::*)()>(&Cinemachine::CinemachineFreeLook::get_State)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(Cinemachine::CinemachineFreeLook*), "get_State", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: Cinemachine::CinemachineFreeLook::get_LookAt
// Il2CppName: get_LookAt
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<::UnityEngine::Transform* (Cinemachine::CinemachineFreeLook::*)()>(&Cinemachine::CinemachineFreeLook::get_LookAt)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(Cinemachine::CinemachineFreeLook*), "get_LookAt", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: Cinemachine::CinemachineFreeLook::set_LookAt
// Il2CppName: set_LookAt
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (Cinemachine::CinemachineFreeLook::*)(::UnityEngine::Transform*)>(&Cinemachine::CinemachineFreeLook::set_LookAt)> {
  static const MethodInfo* get() {
    static auto* value = &::il2cpp_utils::GetClassFromName("UnityEngine", "Transform")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(Cinemachine::CinemachineFreeLook*), "set_LookAt", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{value});
  }
};
// Writing MetadataGetter for method: Cinemachine::CinemachineFreeLook::get_Follow
// Il2CppName: get_Follow
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<::UnityEngine::Transform* (Cinemachine::CinemachineFreeLook::*)()>(&Cinemachine::CinemachineFreeLook::get_Follow)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(Cinemachine::CinemachineFreeLook*), "get_Follow", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: Cinemachine::CinemachineFreeLook::set_Follow
// Il2CppName: set_Follow
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (Cinemachine::CinemachineFreeLook::*)(::UnityEngine::Transform*)>(&Cinemachine::CinemachineFreeLook::set_Follow)> {
  static const MethodInfo* get() {
    static auto* value = &::il2cpp_utils::GetClassFromName("UnityEngine", "Transform")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(Cinemachine::CinemachineFreeLook*), "set_Follow", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{value});
  }
};
// Writing MetadataGetter for method: Cinemachine::CinemachineFreeLook::IsLiveChild
// Il2CppName: IsLiveChild
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<bool (Cinemachine::CinemachineFreeLook::*)(::Cinemachine::ICinemachineCamera*, bool)>(&Cinemachine::CinemachineFreeLook::IsLiveChild)> {
  static const MethodInfo* get() {
    static auto* vcam = &::il2cpp_utils::GetClassFromName("Cinemachine", "ICinemachineCamera")->byval_arg;
    static auto* dominantChildOnly = &::il2cpp_utils::GetClassFromName("System", "Boolean")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(Cinemachine::CinemachineFreeLook*), "IsLiveChild", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{vcam, dominantChildOnly});
  }
};
// Writing MetadataGetter for method: Cinemachine::CinemachineFreeLook::OnTargetObjectWarped
// Il2CppName: OnTargetObjectWarped
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (Cinemachine::CinemachineFreeLook::*)(::UnityEngine::Transform*, ::UnityEngine::Vector3)>(&Cinemachine::CinemachineFreeLook::OnTargetObjectWarped)> {
  static const MethodInfo* get() {
    static auto* target = &::il2cpp_utils::GetClassFromName("UnityEngine", "Transform")->byval_arg;
    static auto* positionDelta = &::il2cpp_utils::GetClassFromName("UnityEngine", "Vector3")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(Cinemachine::CinemachineFreeLook*), "OnTargetObjectWarped", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{target, positionDelta});
  }
};
// Writing MetadataGetter for method: Cinemachine::CinemachineFreeLook::ForceCameraPosition
// Il2CppName: ForceCameraPosition
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (Cinemachine::CinemachineFreeLook::*)(::UnityEngine::Vector3, ::UnityEngine::Quaternion)>(&Cinemachine::CinemachineFreeLook::ForceCameraPosition)> {
  static const MethodInfo* get() {
    static auto* pos = &::il2cpp_utils::GetClassFromName("UnityEngine", "Vector3")->byval_arg;
    static auto* rot = &::il2cpp_utils::GetClassFromName("UnityEngine", "Quaternion")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(Cinemachine::CinemachineFreeLook*), "ForceCameraPosition", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{pos, rot});
  }
};
// Writing MetadataGetter for method: Cinemachine::CinemachineFreeLook::InternalUpdateCameraState
// Il2CppName: InternalUpdateCameraState
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (Cinemachine::CinemachineFreeLook::*)(::UnityEngine::Vector3, float)>(&Cinemachine::CinemachineFreeLook::InternalUpdateCameraState)> {
  static const MethodInfo* get() {
    static auto* worldUp = &::il2cpp_utils::GetClassFromName("UnityEngine", "Vector3")->byval_arg;
    static auto* deltaTime = &::il2cpp_utils::GetClassFromName("System", "Single")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(Cinemachine::CinemachineFreeLook*), "InternalUpdateCameraState", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{worldUp, deltaTime});
  }
};
// Writing MetadataGetter for method: Cinemachine::CinemachineFreeLook::OnTransitionFromCamera
// Il2CppName: OnTransitionFromCamera
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (Cinemachine::CinemachineFreeLook::*)(::Cinemachine::ICinemachineCamera*, ::UnityEngine::Vector3, float)>(&Cinemachine::CinemachineFreeLook::OnTransitionFromCamera)> {
  static const MethodInfo* get() {
    static auto* fromCam = &::il2cpp_utils::GetClassFromName("Cinemachine", "ICinemachineCamera")->byval_arg;
    static auto* worldUp = &::il2cpp_utils::GetClassFromName("UnityEngine", "Vector3")->byval_arg;
    static auto* deltaTime = &::il2cpp_utils::GetClassFromName("System", "Single")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(Cinemachine::CinemachineFreeLook*), "OnTransitionFromCamera", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{fromCam, worldUp, deltaTime});
  }
};
// Writing MetadataGetter for method: Cinemachine::CinemachineFreeLook::New_ctor
// Il2CppName: .ctor
// Cannot get method pointer of value based method overload from template for constructor!
// Try using FindMethod instead!
