// Autogenerated from CppHeaderCreator
// Created by Sc2ad
// =========================================================================
#pragma once
// Begin includes
#include "beatsaber-hook/shared/utils/byref.hpp"
// Completed includes
// Begin forward declares
// Forward declaring namespace: System
namespace System {
  // Forward declaring type: Uri
  class Uri;
}
// Forward declaring namespace: System::Net
namespace System::Net {
  // Forward declaring type: WebRequest
  class WebRequest;
  // Forward declaring type: NetworkCredential
  class NetworkCredential;
  // Forward declaring type: IAuthenticationModule
  class IAuthenticationModule;
}
// Completed forward declares
// Type namespace: System.Net
namespace System::Net {
  // Forward declaring type: ICredentialPolicy
  class ICredentialPolicy;
}
#include "beatsaber-hook/shared/utils/il2cpp-type-check.hpp"
NEED_NO_BOX(::System::Net::ICredentialPolicy);
DEFINE_IL2CPP_ARG_TYPE(::System::Net::ICredentialPolicy*, "System.Net", "ICredentialPolicy");
// Type namespace: System.Net
namespace System::Net {
  // Size: 0x0
  #pragma pack(push, 1)
  // Autogenerated type: System.Net.ICredentialPolicy
  // [TokenAttribute] Offset: FFFFFFFF
  class ICredentialPolicy {
    public:
    // public System.Boolean ShouldSendCredential(System.Uri challengeUri, System.Net.WebRequest request, System.Net.NetworkCredential credential, System.Net.IAuthenticationModule authenticationModule)
    // Offset: 0xFFFFFFFFFFFFFFFF
    bool ShouldSendCredential(::System::Uri* challengeUri, ::System::Net::WebRequest* request, ::System::Net::NetworkCredential* credential, ::System::Net::IAuthenticationModule* authenticationModule);
  }; // System.Net.ICredentialPolicy
  #pragma pack(pop)
}
#include "beatsaber-hook/shared/utils/il2cpp-utils-methods.hpp"
// Writing MetadataGetter for method: System::Net::ICredentialPolicy::ShouldSendCredential
// Il2CppName: ShouldSendCredential
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<bool (System::Net::ICredentialPolicy::*)(::System::Uri*, ::System::Net::WebRequest*, ::System::Net::NetworkCredential*, ::System::Net::IAuthenticationModule*)>(&System::Net::ICredentialPolicy::ShouldSendCredential)> {
  static const MethodInfo* get() {
    static auto* challengeUri = &::il2cpp_utils::GetClassFromName("System", "Uri")->byval_arg;
    static auto* request = &::il2cpp_utils::GetClassFromName("System.Net", "WebRequest")->byval_arg;
    static auto* credential = &::il2cpp_utils::GetClassFromName("System.Net", "NetworkCredential")->byval_arg;
    static auto* authenticationModule = &::il2cpp_utils::GetClassFromName("System.Net", "IAuthenticationModule")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(System::Net::ICredentialPolicy*), "ShouldSendCredential", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{challengeUri, request, credential, authenticationModule});
  }
};
