// Autogenerated from CppHeaderCreator
// Created by Sc2ad
// =========================================================================
#pragma once
// Begin includes
#include "beatsaber-hook/shared/utils/typedefs.h"
#include "beatsaber-hook/shared/utils/byref.hpp"
#include "beatsaber-hook/shared/utils/il2cpp-utils-methods.hpp"
#include "beatsaber-hook/shared/utils/il2cpp-utils-properties.hpp"
#include "beatsaber-hook/shared/utils/il2cpp-utils-fields.hpp"
#include "beatsaber-hook/shared/utils/utils.h"
#include "beatsaber-hook/shared/utils/typedefs-string.hpp"
// Completed includes
// Begin forward declares
// Forward declaring namespace: System::Net
namespace System::Net {
  // Forward declaring type: WebExceptionStatus
  struct WebExceptionStatus;
  // Forward declaring type: HttpStatusCode
  struct HttpStatusCode;
  // Forward declaring type: FtpStatusCode
  struct FtpStatusCode;
}
// Completed forward declares
// Type namespace: System.Net
namespace System::Net {
  // Forward declaring type: NetRes
  class NetRes;
}
#include "beatsaber-hook/shared/utils/il2cpp-type-check.hpp"
NEED_NO_BOX(::System::Net::NetRes);
DEFINE_IL2CPP_ARG_TYPE(::System::Net::NetRes*, "System.Net", "NetRes");
// Type namespace: System.Net
namespace System::Net {
  // Size: 0x10
  #pragma pack(push, 1)
  // Autogenerated type: System.Net.NetRes
  // [TokenAttribute] Offset: FFFFFFFF
  class NetRes : public ::Il2CppObject {
    public:
    // private System.Void .ctor()
    // Offset: 0xEDB80C
    template<::il2cpp_utils::CreationType creationType = ::il2cpp_utils::CreationType::Temporary>
    static NetRes* New_ctor() {
      static auto ___internal__logger = ::Logger::get().WithContext("::System::Net::NetRes::.ctor");
      return THROW_UNLESS((::il2cpp_utils::New<NetRes*, creationType>()));
    }
    // static public System.String GetWebStatusString(System.String Res, System.Net.WebExceptionStatus Status)
    // Offset: 0xEDB814
    static ::StringW GetWebStatusString(::StringW Res, ::System::Net::WebExceptionStatus Status);
    // static public System.String GetWebStatusString(System.Net.WebExceptionStatus Status)
    // Offset: 0xEDB8E0
    static ::StringW GetWebStatusString(::System::Net::WebExceptionStatus Status);
    // static public System.String GetWebStatusCodeString(System.Net.HttpStatusCode statusCode, System.String statusDescription)
    // Offset: 0xEDB950
    static ::StringW GetWebStatusCodeString(::System::Net::HttpStatusCode statusCode, ::StringW statusDescription);
    // static public System.String GetWebStatusCodeString(System.Net.FtpStatusCode statusCode, System.String statusDescription)
    // Offset: 0xEDBB2C
    static ::StringW GetWebStatusCodeString(::System::Net::FtpStatusCode statusCode, ::StringW statusDescription);
  }; // System.Net.NetRes
  #pragma pack(pop)
}
#include "beatsaber-hook/shared/utils/il2cpp-utils-methods.hpp"
// Writing MetadataGetter for method: System::Net::NetRes::New_ctor
// Il2CppName: .ctor
// Cannot get method pointer of value based method overload from template for constructor!
// Try using FindMethod instead!
// Writing MetadataGetter for method: System::Net::NetRes::GetWebStatusString
// Il2CppName: GetWebStatusString
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<::StringW (*)(::StringW, ::System::Net::WebExceptionStatus)>(&System::Net::NetRes::GetWebStatusString)> {
  static const MethodInfo* get() {
    static auto* Res = &::il2cpp_utils::GetClassFromName("System", "String")->byval_arg;
    static auto* Status = &::il2cpp_utils::GetClassFromName("System.Net", "WebExceptionStatus")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(System::Net::NetRes*), "GetWebStatusString", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{Res, Status});
  }
};
// Writing MetadataGetter for method: System::Net::NetRes::GetWebStatusString
// Il2CppName: GetWebStatusString
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<::StringW (*)(::System::Net::WebExceptionStatus)>(&System::Net::NetRes::GetWebStatusString)> {
  static const MethodInfo* get() {
    static auto* Status = &::il2cpp_utils::GetClassFromName("System.Net", "WebExceptionStatus")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(System::Net::NetRes*), "GetWebStatusString", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{Status});
  }
};
// Writing MetadataGetter for method: System::Net::NetRes::GetWebStatusCodeString
// Il2CppName: GetWebStatusCodeString
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<::StringW (*)(::System::Net::HttpStatusCode, ::StringW)>(&System::Net::NetRes::GetWebStatusCodeString)> {
  static const MethodInfo* get() {
    static auto* statusCode = &::il2cpp_utils::GetClassFromName("System.Net", "HttpStatusCode")->byval_arg;
    static auto* statusDescription = &::il2cpp_utils::GetClassFromName("System", "String")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(System::Net::NetRes*), "GetWebStatusCodeString", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{statusCode, statusDescription});
  }
};
// Writing MetadataGetter for method: System::Net::NetRes::GetWebStatusCodeString
// Il2CppName: GetWebStatusCodeString
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<::StringW (*)(::System::Net::FtpStatusCode, ::StringW)>(&System::Net::NetRes::GetWebStatusCodeString)> {
  static const MethodInfo* get() {
    static auto* statusCode = &::il2cpp_utils::GetClassFromName("System.Net", "FtpStatusCode")->byval_arg;
    static auto* statusDescription = &::il2cpp_utils::GetClassFromName("System", "String")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(System::Net::NetRes*), "GetWebStatusCodeString", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{statusCode, statusDescription});
  }
};
