// Autogenerated from CppHeaderCreator
// Created by Sc2ad
// =========================================================================
#pragma once
// Begin includes
#include "beatsaber-hook/shared/utils/byref.hpp"
// Completed includes
// Type namespace: System.Security
namespace System::Security {
  // Forward declaring type: IPermission
  class IPermission;
}
#include "beatsaber-hook/shared/utils/il2cpp-type-check.hpp"
NEED_NO_BOX(::System::Security::IPermission);
DEFINE_IL2CPP_ARG_TYPE(::System::Security::IPermission*, "System.Security", "IPermission");
// Type namespace: System.Security
namespace System::Security {
  // Size: 0x0
  #pragma pack(push, 1)
  // Autogenerated type: System.Security.IPermission
  // [TokenAttribute] Offset: FFFFFFFF
  // [ComVisibleAttribute] Offset: A52CC0
  class IPermission {
    public:
  }; // System.Security.IPermission
  #pragma pack(pop)
}
#include "beatsaber-hook/shared/utils/il2cpp-utils-methods.hpp"
